### ISSUE TITLE
Compatible with Moq?

### ISSUE THREAD

**Issue by byang223** [bazelbuild/rules_dotnet#117]
I'm trying to set up `dotnet_nunit_test` with moq. I have the following in my WORKSPACE

```
dotnet_nuget_new(
    name = "moq",
    package = "moq",
    version = "4.10.0",
    source = "https://www.nuget.org/api/v2/package",
    build_file_content = """
package(default_visibility = [ "//visibility:public" ])
load("@io_bazel_rules_dotnet//dotnet:defs.bzl", "dotnet_import_library")

dotnet_import_library(
    name = "lib",
    src = "lib/net45/Moq.dll",
)
    """
)
```

I refer to this by adding the following line to test dependency

```
"@moq//:lib",
```

However, I'm getting the following message:

```
error CS0009: Metadata file `/private/var/tmp/_bazel_byang/2fc73dc3f7e41d43b739acd65e005cdf/execroot/grail/external/moq/lib/net45/Moq.dll' does not contain valid metadata
```

The contents of moq/net45 include a Moq.dll, Moq.xml and Moq.pdb. Do these other files need to be referenced?

Any insight would be greatly appreciated. Thanks!

**Comment by tomaszstrejczek** [comment]
Could you provide the BUILD directive you use to compile the tests? Do you try to compile core, .NET or Mono library? It's usually easier to use [nuget2bazel](https://github.com/bazelbuild/rules_dotnet/blob/master/tools/nuget2bazel/README.rst) tool . It generates [nuget_package](https://github.com/bazelbuild/rules_dotnet/blob/master/dotnet/workspace.rst#nuget_package) rules that are easier to use.
Moq has quite a number of dependencies. See the output [here](https://gist.github.com/tomaszstrejczek/f609fc43a37cdaa69aba5dd0b6178849).

**Comment by byang223** [comment]
Here's my BUILD file

```
dotnet_nunit_test(
    name = "test_lib",
    srcs = ["SomeTest.cs"],
    deps = [
        "@io_bazel_rules_dotnet//dotnet/stdlib:System.Core.dll",
        "@moq//:lib",
        "@newtonsoft.json//:lib",
        "@nunit2//:nunit.framework",
    ],
)
```

I'm using `dotnet`. I'm also on Mac OS and I'm not sure if that works with nuget2bazel. I've been using dotnet_nuget_new with my other packages and those have all seemed to work okay.

**Comment by byang223** [comment]
I tried using `nuget2bazel` and I'm getting the following error

```
System.ArgumentNullException: Value cannot be null.
Parameter name: path1
   at System.IO.Path.Combine(String path1, String path2)
   at Microsoft.DotNet.Configurer.CliFallbackFolderPathCalculator.get_DotnetUserProfileFolderPath()
   at Microsoft.DotNet.Configurer.FirstTimeUseNoticeSentinel..ctor(CliFallbackFolderPathCalculator cliFallbackFolderPathCalculator)
   at Microsoft.DotNet.Cli.Program.ProcessArgs(String[] args, ITelemetry telemetryClient)
   at Microsoft.DotNet.Cli.Program.Main(String[] args)
```

The command I used to call is 

```
bazel run //tools/nuget2bazel:v2.1.200_nuget2bazel -- add moq 4.10.0 -p /Users/byang/code/rules_dotnet
```

Is the tool compatible with dotnet? I notice that there are only core_binary targets and not dotnet_binary target

**Comment by byang223** [comment]
It seems the issue above is known. I'll keep trying to get this to work.

In the mean time, I tried using the gist you pasted above for my moq test and I'm getting another issue.

```
target 'system.valuetuple.dll' not declared in package 'dotnet/stdlib' defined by /private/var/tmp/_bazel_byang/2fc73dc3f7e41d43b739acd65e005cdf/external/io_bazel_rules_dotnet/dotnet/stdlib/BUILD.bazel and referenced by '@moq//:mono'
```

It looks like it's trying to use system.valuetuple.dll and system.threading.tasks.extensions.dll in stdlib though they don't exist. Is it possible to add those dlls?

**Comment by tomaszstrejczek** [comment]
Closing due to inactivity.
