### ISSUE TITLE
Nuget2bazel gives System.PlatformNotSupportedException

### ISSUE THREAD

**Issue by aaliddell** [bazelbuild/rules_dotnet#140]
When running on a Linux host, using `bazel run @io_bazel_rules_dotnet//tools/nuget2bazel:v2.2.101_nuget2bazel.exe add ...` gives the following error:

```
Unhandled Exception: System.AggregateException: One or more errors occurred. (Unable to load the service index for source https://api.nuget.org/v3/index.json.) ---> NuGet.Protocol.Core.Types.FatalProtocolException: Unable to load the service index for source https://api.nuget.org/v3/index.json. ---> System.PlatformNotSupportedException: Operation is not supported on this platform.
   at System.Net.SystemWebProxy.GetProxy(Uri destination)
   at NuGet.Configuration.ProxyCache.IsSystemProxySet(Uri uri)
   at NuGet.Configuration.ProxyCache.GetProxy(Uri sourceUri)
   at NuGet.Protocol.HttpHandlerResourceV3Provider.CreateResource(PackageSource packageSource)
   at NuGet.Protocol.HttpHandlerResourceV3Provider.TryCreate(SourceRepository source, CancellationToken token)
   at NuGet.Protocol.Core.Types.SourceRepository.GetResourceAsync[T](CancellationToken token)
   at NuGet.Protocol.Core.Types.SourceRepository.GetResourceAsync[T]()
   at NuGet.Protocol.HttpSource.CreateHttpClientAsync()
   at NuGet.Protocol.HttpSource.EnsureHttpClientAsync()
   at NuGet.Protocol.HttpSource.GetThrottledResponse(Func`1 requestFactory, TimeSpan requestTimeout, TimeSpan downloadTimeout, Int32 maxTries, Guid sessionId, ILogger log, CancellationToken cancellationToken)
   at NuGet.Protocol.HttpSource.<>c__DisplayClass14_0`1.<<GetAsync>b__0>d.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at NuGet.Common.ConcurrencyUtilities.ExecuteWithFileLockedAsync[T](String filePath, Func`2 action, CancellationToken token)
   at NuGet.Protocol.HttpSource.GetAsync[T](HttpSourceCachedRequest request, Func`2 processAsync, ILogger log, CancellationToken token)
   at NuGet.Protocol.ServiceIndexResourceV3Provider.GetServiceIndexResourceV3(SourceRepository source, DateTime utcNow, ILogger log, CancellationToken token)
   --- End of inner exception stack trace ---
   at NuGet.Protocol.ServiceIndexResourceV3Provider.GetServiceIndexResourceV3(SourceRepository source, DateTime utcNow, ILogger log, CancellationToken token)
   at NuGet.Protocol.ServiceIndexResourceV3Provider.TryCreate(SourceRepository source, CancellationToken token)
   at NuGet.Protocol.Core.Types.SourceRepository.GetResourceAsync[T](CancellationToken token)
   at NuGet.Protocol.PackageMetadataResourceV3Provider.TryCreate(SourceRepository source, CancellationToken token)
   at NuGet.Protocol.Core.Types.SourceRepository.GetResourceAsync[T](CancellationToken token)
   at NuGet.Protocol.Core.Types.SourceRepository.GetResourceAsync[T]()
   at nuget2bazel.AddCommand.Do(String package, String version, String rootPath, String mainFile, Boolean skipSha256)
   --- End of inner exception stack trace ---
   at System.Threading.Tasks.Task.Wait(Int32 millisecondsTimeout, CancellationToken cancellationToken)
   at System.Threading.Tasks.Task.Wait()
   at nuget2bazel.Program.<>c.<Main>b__0_0(AddVerb opts)
   at nuget2bazel.Program.Main(String[] args)
```

I have tested all the versions available and all give the same or similar results.

**Comment by lshulyayeva** [comment]
I'm experiencing this issue trying out nuget2bazel for the first time; not sure if this is some edge case that I may be able to work around or if this makes nuget2bazel generally unusable?

**Comment by tomaszstrejczek** [comment]
@lshulyayeva Could you try the latest version (0.0.4)? I've just tried:
bazel run --spawn_strategy=standalone @io_bazel_rules_dotnet//tools/nuget2bazel:nuget2bazel.exe -- add -p ~/tmp CommandLineParser 2.6.0
and it seems to work on Ubuntu.

**Comment by tomaszstrejczek** [comment]
Closing due to inavtivity.
