### ISSUE TITLE
The type or namespace name 'Management' does not exist in the namespace 'System' (are you missing an assembly reference?)

### ISSUE THREAD

**Issue by wbiker** [bazelbuild/rules_dotnet#163]
I am getting:
```
C:\...\source\CSharpPowerShellExecutor\PowerShellExecutor.cs(10,14): error CS0234: The type or namespace name 'Management' does not exist in the namespace 'System' (are you missing an assembly reference?)
```
I found a reference in macro.bzl:
https://github.com/bazelbuild/rules_dotnet/blob/master/dotnet/stdlib.net/macro.bzl#L77
But I do not know if that means the assembly reference is automatically added to the compiler, or do I have to add them somehow?
Adding an entry like:
```
"@io_bazel_rules_dotnet//dotnet/stdlib.net/net461:system.runtime.dll"
```
does not work. And could not find any documentation for references either.

Sorry, when that is a silly question, I am still just starting with C# and bazel.
Thanks for your help,
Wolfgang

**Comment by wbiker** [comment]
OK after adding 
```
"@io_bazel_rules_dotnet//dotnet/stdlib.net:system.management.dll",
```
it works.
But now system.management.automation.dll is missing and that is not already in the code. A	  ```
"@io_bazel_rules_dotnet//dotnet/stdlib.net:system.management.automation.dll",
```
just yields an error. 
How can I add the missing assembly to rules_dotnet?

**Comment by wbiker** [comment]
According to the documentation:
https://github.com/bazelbuild/rules_dotnet/blob/master/docs/runtime.rst
The system.management.automation assembly is not linked because it already exists in GAC.
That is probably not a rules_dotnet question, but how can I compile my executable with a GAC assembly reference?

**Comment by tomaszstrejczek** [comment]
I think that system.management.automation.dll is not a part of .NET Framework. The easiest way to use it is to find a proper nuget package and use [nuget2bazel](https://github.com/bazelbuild/rules_dotnet/blob/master/tools/nuget2bazel/README.rst) to import it.
However, I haven't found a nuget package for system.management.automation.dll for .NET Framework. [This one](https://www.nuget.org/packages/System.Management.Automation/7.0.0) is only for .NET Core. 
Therefore, I see two options:
1) Switching to .NET Core and using nuget
2) Installing the Management SDK separately and then using [net_import_library](https://github.com/bazelbuild/rules_dotnet/blob/master/dotnet/core.rst#id27).
Option 2 is much more difficult because the SDK is not distributed as an archive file. Probably it would be necessary to write a special workspace rule to locate the sdk on the local machine and link it as an external dependency.

**Comment by wbiker** [comment]
Many thanks for your help.
I think I will go with option 1.

**Comment by wbiker** [comment]
OK, after looking into that it looks like the option 2 is the easiest one.
Unfortunately, after adding net_gac4 rule, the Bazel Server crashes:
´´´
FAILED: Build did NOT complete successfully (21 packages loaded, 43 targets configured)
    currently loading: @io_bazel_rules_dotnet//dotnet/stdlib.net
Internal error thrown during build. Printing stack trace: java.lang.RuntimeException: Unrecoverable error while evaluating node 'PACKAGE:' (requested by nodes '//source/CSharpPowerShellExecutor:CSharpPowerShellExecutor.exe BuildConfigurationValue.Key[11beb687ec497e612ebe1cd4752ad0b47ebb2fb05a7e5c26c6d2572d30aaf560] false')
        at com.google.devtools.build.skyframe.AbstractParallelEvaluator$Evaluate.run(AbstractParallelEvaluator.java:531)
        at com.google.devtools.build.lib.concurrent.AbstractQueueVisitor$WrappedRunnable.run(AbstractQueueVisitor.java:399)
        at java.base/java.util.concurrent.ForkJoinTask$AdaptedRunnableAction.exec(Unknown Source)
        at java.base/java.util.concurrent.ForkJoinTask.doExec(Unknown Source)
        at java.base/java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(Unknown Source)
        at java.base/java.util.concurrent.ForkJoinPool.scan(Unknown Source)
        at java.base/java.util.concurrent.ForkJoinPool.runWorker(Unknown Source)
        at java.base/java.util.concurrent.ForkJoinWorkerThread.run(Unknown Source)
Caused by: java.lang.IllegalArgumentException: 'repo_mapping' may only be used in the //external package
        at com.google.devtools.build.lib.packages.Package.finishInit(Package.java:410)
        at com.google.devtools.build.lib.packages.Package.access$2900(Package.java:80)
        at com.google.devtools.build.lib.packages.Package$Builder.finishBuild(Package.java:1537)
        at com.google.devtools.build.lib.skyframe.PackageFunction.compute(PackageFunction.java:541)
        at com.google.devtools.build.skyframe.AbstractParallelEvaluator$Evaluate.run(AbstractParallelEvaluator.java:454)
        ... 7 more
java.lang.RuntimeException: Unrecoverable error while evaluating node 'PACKAGE:' (requested by nodes '//source/CSharpPowerShellExecutor:CSharpPowerShellExecutor.exe BuildConfigurationValue.Key[11beb687ec497e612ebe1cd4752ad0b47ebb2fb05a7e5c26c6d2572d30aaf560] false')
        at com.google.devtools.build.skyframe.AbstractParallelEvaluator$Evaluate.run(AbstractParallelEvaluator.java:531)
        at com.google.devtools.build.lib.concurrent.AbstractQueueVisitor$WrappedRunnable.run(AbstractQueueVisitor.java:399)
        at java.base/java.util.concurrent.ForkJoinTask$AdaptedRunnableAction.exec(Unknown Source)
        at java.base/java.util.concurrent.ForkJoinTask.doExec(Unknown Source)
        at java.base/java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(Unknown Source)
        at java.base/java.util.concurrent.ForkJoinPool.scan(Unknown Source)
        at java.base/java.util.concurrent.ForkJoinPool.runWorker(Unknown Source)
        at java.base/java.util.concurrent.ForkJoinWorkerThread.run(Unknown Source)
Caused by: java.lang.IllegalArgumentException: 'repo_mapping' may only be used in the //external package
        at com.google.devtools.build.lib.packages.Package.finishInit(Package.java:410)
        at com.google.devtools.build.lib.packages.Package.access$2900(Package.java:80)
        at com.google.devtools.build.lib.packages.Package$Builder.finishBuild(Package.java:1537)
        at com.google.devtools.build.lib.skyframe.PackageFunction.compute(PackageFunction.java:541)
FAILED: Build did NOT complete successfully (21 packages loaded, 43 targets configured)
    currently loading: @io_bazel_rules_dotnet//dotnet/stdlib.net
´´´
I created a BUILD.bazel file next to the WORKSPACE one and added:
´´´
net_gac4(name = "System.Management.Automation.dll", version = "3.0.0.0", token = "31bf3856ad364e35")
´´´
Im project BUILD file I added the deps:
```
  "//:System.Management.Automation.dll",
´´´
Is there a mistake on my side?
Sorry and thanks for your help!
