### ISSUE TITLE
net_gac4 causes Bazel server to crash

### ISSUE THREAD

**Issue by wbiker** [bazelbuild/rules_dotnet#166]
After adding net_gac4 rule, the Bazel Server crashes:
```
FAILED: Build did NOT complete successfully (21 packages loaded, 43 targets configured)
    currently loading: @io_bazel_rules_dotnet//dotnet/stdlib.net
Internal error thrown during build. Printing stack trace: java.lang.RuntimeException: Unrecoverable error while evaluating node 'PACKAGE:' (requested by nodes '//source/CSharpPowerShellExecutor:CSharpPowerShellExecutor.exe BuildConfigurationValue.Key[11beb687ec497e612ebe1cd4752ad0b47ebb2fb05a7e5c26c6d2572d30aaf560] false')
        at com.google.devtools.build.skyframe.AbstractParallelEvaluator$Evaluate.run(AbstractParallelEvaluator.java:531)
        at com.google.devtools.build.lib.concurrent.AbstractQueueVisitor$WrappedRunnable.run(AbstractQueueVisitor.java:399)
        at java.base/java.util.concurrent.ForkJoinTask$AdaptedRunnableAction.exec(Unknown Source)
        at java.base/java.util.concurrent.ForkJoinTask.doExec(Unknown Source)
        at java.base/java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(Unknown Source)
        at java.base/java.util.concurrent.ForkJoinPool.scan(Unknown Source)
        at java.base/java.util.concurrent.ForkJoinPool.runWorker(Unknown Source)
        at java.base/java.util.concurrent.ForkJoinWorkerThread.run(Unknown Source)
Caused by: java.lang.IllegalArgumentException: 'repo_mapping' may only be used in the //external package
        at com.google.devtools.build.lib.packages.Package.finishInit(Package.java:410)
        at com.google.devtools.build.lib.packages.Package.access$2900(Package.java:80)
        at com.google.devtools.build.lib.packages.Package$Builder.finishBuild(Package.java:1537)
        at com.google.devtools.build.lib.skyframe.PackageFunction.compute(PackageFunction.java:541)
        at com.google.devtools.build.skyframe.AbstractParallelEvaluator$Evaluate.run(AbstractParallelEvaluator.java:454)
        ... 7 more
java.lang.RuntimeException: Unrecoverable error while evaluating node 'PACKAGE:' (requested by nodes '//source/CSharpPowerShellExecutor:CSharpPowerShellExecutor.exe BuildConfigurationValue.Key[11beb687ec497e612ebe1cd4752ad0b47ebb2fb05a7e5c26c6d2572d30aaf560] false')
        at com.google.devtools.build.skyframe.AbstractParallelEvaluator$Evaluate.run(AbstractParallelEvaluator.java:531)
        at com.google.devtools.build.lib.concurrent.AbstractQueueVisitor$WrappedRunnable.run(AbstractQueueVisitor.java:399)
        at java.base/java.util.concurrent.ForkJoinTask$AdaptedRunnableAction.exec(Unknown Source)
        at java.base/java.util.concurrent.ForkJoinTask.doExec(Unknown Source)
        at java.base/java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(Unknown Source)
        at java.base/java.util.concurrent.ForkJoinPool.scan(Unknown Source)
        at java.base/java.util.concurrent.ForkJoinPool.runWorker(Unknown Source)
        at java.base/java.util.concurrent.ForkJoinWorkerThread.run(Unknown Source)
Caused by: java.lang.IllegalArgumentException: 'repo_mapping' may only be used in the //external package
        at com.google.devtools.build.lib.packages.Package.finishInit(Package.java:410)
        at com.google.devtools.build.lib.packages.Package.access$2900(Package.java:80)
        at com.google.devtools.build.lib.packages.Package$Builder.finishBuild(Package.java:1537)
        at com.google.devtools.build.lib.skyframe.PackageFunction.compute(PackageFunction.java:541)
FAILED: Build did NOT complete successfully (21 packages loaded, 43 targets configured)
    currently loading: @io_bazel_rules_dotnet//dotnet/stdlib.net
```
I created a BUILD.bazel file next to the WORKSPACE one and added:
```
net_gac4(name = "System.Management.Automation", version = "3.0.0.0", token = "31bf3856ad364e35")
```
Im project BUILD file I added the deps:
```
  "//:System.Management.Automation",
```
The assembly in question exists in:
C:\Windows\Microsoft.NET\assembly\GAC_MSIL\System.Management.Automation\v4.0_3.0.0.0__31bf3856ad364e35\System.Management.Automation.dll

**Comment by wbiker** [comment]
Not Bazel related.
