### ISSUE TITLE
Try use without net_core and mono

### ISSUE THREAD

**Issue by lupin-de-mid** [bazelbuild/rules_dotnet#185]
So i have 
WORKSPACE
```
load("@bazel_tools//tools/build_defs/repo:git.bzl", "git_repository")
git_repository(
     name = "io_bazel_rules_dotnet",
     remote = "https://github.com/bazelbuild/rules_dotnet",
     branch = "master",
)
load("@io_bazel_rules_dotnet//dotnet:deps.bzl", "dotnet_repositories")
dotnet_repositories()
load("@io_bazel_rules_dotnet//dotnet:defs.bzl", "net_register_sdk",  "dotnet_register_toolchains")
dotnet_register_toolchains()
net_register_sdk("net46")

```

BUILD
```
load("@io_bazel_rules_dotnet//dotnet:defs.bzl", "net_binary")
net_binary(
    name = "a.exe",
    srcs = [  "a.cs",   ],
)
```

a.cs (is irrelevant, but)
```
class A {}
```
So  receive  this

```
bazel build //:a.exe
INFO: Repository net_sdk instantiated at:
  no stack (--record_rule_instantiation_callstack not enabled)
Repository rule net_download_sdk defined at:
  C:/users/user/_bazel_user/625t4kvk/external/io_bazel_rules_dotnet/dotnet/private/sdk_net.bzl:50:35: in <toplevel>
INFO: Repository 'net_sdk' used the following cache hits instead of downloading the corresponding file.
 * Hash '854d162cbe3c90100922c970ba593631f2d106f7b757a99425d50dc5cdafbdc0' for https://www.nuget.org/api/v2/package/Microsoft.Net.Compilers/2.10.0/
If the definition of 'net_sdk' was updated, verify that the hashes were also updated.
ERROR: An error occurred during the fetch of repository 'net_sdk':
   Traceback (most recent call last):
        File "C:/users/user/_bazel_user/625t4kvk/external/io_bazel_rules_dotnet/dotnet/private/sdk_net.bzl", line 38
                _detect_net_tools(ctx, <1 more arguments>)
        File "C:/users/user/_bazel_user/625t4kvk/external/io_bazel_rules_dotnet/dotnet/private/sdk_net.bzl", line 13, in _detect_net_tools
                fail(<1 more arguments>)
Failed to find .net tools 4.8 in default location C:/Program Files (x86)/Microsoft SDKs/Windows/v10.0A/bin/NETFX 4.8 Tools
ERROR: X:/users/user/downloads/a/BUILD:3:11: //:a.exe depends on @net_sdk//:native_deps in repository @net_sdk which failed to fetch. no such package '@net_sdk//': Traceback (most recent call last):
        File "C:/users/user/_bazel_user/625t4kvk/external/io_bazel_rules_dotnet/dotnet/private/sdk_net.bzl", line 38
                _detect_net_tools(ctx, <1 more arguments>)
        File "C:/users/user/_bazel_user/625t4kvk/external/io_bazel_rules_dotnet/dotnet/private/sdk_net.bzl", line 13, in _detect_net_tools
                fail(<1 more arguments>)
Failed to find .net tools 4.8 in default location C:/Program Files (x86)/Microsoft SDKs/Windows/v10.0A/bin/NETFX 4.8 Tools
ERROR: Analysis of target '//:a.exe' failed; build aborted: Analysis failed
INFO: Elapsed time: 2.828s
INFO: 0 processes.
FAILED: Build did NOT complete successfully (0 packages loaded, 0 targets configured)
```

How it related to 4.6 from workspace?
"Full" source of sample
[a.zip](https://github.com/bazelbuild/rules_dotnet/files/4805964/a.zip)

**Comment by tomaszstrejczek** [comment]
net_binary() uses a default .NET SDK which is set to 4.8. If you want to use a different version it is required to specify appropriate context attributes:
```
net_binary(
    name = "a.exe",
    srcs = [  "a.cs",   ],
    dotnet_context_data = "@io_bazel_rules_dotnet//:net_context_data_net46",
    native_deps = "@net_sdk_net46//:native_deps",
 )
```

**Comment by lupin-de-mid** [comment]
I'll try it tomorrow

**Comment by lupin-de-mid** [comment]
I update  BUILD to 
```
load("@io_bazel_rules_dotnet//dotnet:defs.bzl", "net_binary")

net_binary(
    name = "a.exe",
    srcs = [  "a.cs",   ],
    dotnet_context_data = "@io_bazel_rules_dotnet//:net_context_data_net46",
    native_deps = "@net_sdk_net46//:native_deps",
 )
```
And than

```
bazel build //:a.exe
ERROR: X:/work/github/rules_dotnet/docs/examples/mono/BUILD:3:11: no such package '@net_sdk_net46//': The repository '@net_sdk_net46' could not be resolved and referenced by '//:a.exe'
ERROR: Analysis of target '//:a.exe' failed; build aborted: Analysis failed
INFO: Elapsed time: 0.389s
INFO: 0 processes.
FAILED: Build did NOT complete successfully (3 packages loaded, 4 targets configured)
```

I try change workspace (adding name = "net_sdk_net46")  
```
load("@bazel_tools//tools/build_defs/repo:git.bzl", "git_repository")
git_repository(
     name = "io_bazel_rules_dotnet",
     remote = "https://github.com/bazelbuild/rules_dotnet",
     branch = "master",
)
load("@io_bazel_rules_dotnet//dotnet:deps.bzl", "dotnet_repositories")
dotnet_repositories()
load("@io_bazel_rules_dotnet//dotnet:defs.bzl", "net_register_sdk",  "dotnet_register_toolchains")
dotnet_register_toolchains()

net_register_sdk("net46", name = "net_sdk_net46")
```

and than receive same error as at start of my excersize

```
bazel build //:a.exe
INFO: Repository net_sdk_net46 instantiated at:
  no stack (--record_rule_instantiation_callstack not enabled)
Repository rule net_download_sdk defined at:
  C:/users/user/_bazel_user/wwnhhnsh/external/io_bazel_rules_dotnet/dotnet/private/sdk_net.bzl:50:35: in <toplevel>
INFO: Repository 'net_sdk_net46' used the following cache hits instead of downloading the corresponding file.
 * Hash '854d162cbe3c90100922c970ba593631f2d106f7b757a99425d50dc5cdafbdc0' for https://www.nuget.org/api/v2/package/Microsoft.Net.Compilers/2.10.0/
If the definition of 'net_sdk_net46' was updated, verify that the hashes were also updated.
ERROR: An error occurred during the fetch of repository 'net_sdk_net46':
   Traceback (most recent call last):
        File "C:/users/user/_bazel_user/wwnhhnsh/external/io_bazel_rules_dotnet/dotnet/private/sdk_net.bzl", line 38
                _detect_net_tools(ctx, <1 more arguments>)
        File "C:/users/user/_bazel_user/wwnhhnsh/external/io_bazel_rules_dotnet/dotnet/private/sdk_net.bzl", line 13, in _detect_net_tools
                fail(<1 more arguments>)
Failed to find .net tools 4.8 in default location C:/Program Files (x86)/Microsoft SDKs/Windows/v10.0A/bin/NETFX 4.8 Tools
ERROR: X:/work/github/rules_dotnet/docs/examples/mono/BUILD:3:11: //:a.exe depends on @net_sdk_net46//:native_deps in repository @net_sdk_net46 which failed to fetch. no such package '@net_sdk_net46//': Traceback (most recent call last):
        File "C:/users/user/_bazel_user/wwnhhnsh/external/io_bazel_rules_dotnet/dotnet/private/sdk_net.bzl", line 38
                _detect_net_tools(ctx, <1 more arguments>)
        File "C:/users/user/_bazel_user/wwnhhnsh/external/io_bazel_rules_dotnet/dotnet/private/sdk_net.bzl", line 13, in _detect_net_tools
                fail(<1 more arguments>)
Failed to find .net tools 4.8 in default location C:/Program Files (x86)/Microsoft SDKs/Windows/v10.0A/bin/NETFX 4.8 Tools
ERROR: Analysis of target '//:a.exe' failed; build aborted: Analysis failed
INFO: Elapsed time: 2.652s
INFO: 0 processes.
FAILED: Build did NOT complete successfully (7 packages loaded, 4 targets configured)
```

**Comment by lupin-de-mid** [comment]
I update 
WORKSPACE
```
load("@bazel_tools//tools/build_defs/repo:git.bzl", "git_repository")
git_repository(
     name = "io_bazel_rules_dotnet",
     remote = "https://github.com/bazelbuild/rules_dotnet",
     branch = "master",
)
load("@io_bazel_rules_dotnet//dotnet:deps.bzl", "dotnet_repositories")
dotnet_repositories()
load("@io_bazel_rules_dotnet//dotnet:defs.bzl", "net_register_sdk",  "dotnet_register_toolchains")
dotnet_register_toolchains()
net_register_sdk("net46", name = "net_sdk_net46", tools_version = "net462")
```

BUILD
```
load("@io_bazel_rules_dotnet//dotnet:defs.bzl", "net_binary")

net_binary(
    name = "a.exe",
    srcs = [  "a.cs",   ],
    dotnet_context_data = "@io_bazel_rules_dotnet//:net_context_data_net46",
    native_deps = "@net_sdk_net46//:native_deps",
 )
```
a.cs
```
using System;

namespace b
{
	class a
	{
		static void Main(string[] args)
		{
			Console.WriteLine("Hello World!");
		}
	}
}

```

output
```
 bazel build //:a.exe
INFO: Analyzed target //:a.exe (0 packages loaded, 0 targets configured).
INFO: Found 1 target...
ERROR: X:/work/github/rules_dotnet/docs/examples/mono/BUILD:3:11: Compiling net :a.exe failed (Exit 1)
a.cs(1,7): error CS0246: The type or namespace name 'System' could not be found (are you missing a using directive or an assembly reference?)
a.cs(6,18): error CS0518: Predefined type 'System.Object' is not defined or imported
a.cs(8,26): error CS0518: Predefined type 'System.String' is not defined or imported
a.cs(8,16): error CS0518: Predefined type 'System.Void' is not defined or imported
Target //:a.exe failed to build
Use --verbose_failures to see the command lines of failed build steps.
INFO: Elapsed time: 0.534s, Critical Path: 0.34s
INFO: 0 processes.
FAILED: Build did NOT complete successfully  
```

**Comment by lupin-de-mid** [comment]
I update 
WORKSPACE
```
load("@bazel_tools//tools/build_defs/repo:git.bzl", "git_repository")
git_repository(
     name = "io_bazel_rules_dotnet",
     remote = "https://github.com/bazelbuild/rules_dotnet",
     branch = "master",
)
load("@io_bazel_rules_dotnet//dotnet:deps.bzl", "dotnet_repositories")
dotnet_repositories()
load("@io_bazel_rules_dotnet//dotnet:defs.bzl", "net_register_sdk",  "dotnet_register_toolchains")
dotnet_register_toolchains()
net_register_sdk("net46", name = "net_sdk_net46", tools_version = "net462")
```

BUILD
```
load("@io_bazel_rules_dotnet//dotnet:defs.bzl", "net_binary")

net_binary(
    name = "a.exe",
    srcs = [  "a.cs",   ],
    dotnet_context_data = "@io_bazel_rules_dotnet//:net_context_data_net46",
    native_deps = "@net_sdk_net46//:native_deps",
 )
```
a.cs
```
using System;

namespace b
{
	class a
	{
		static void Main(string[] args)
		{
			Console.WriteLine("Hello World!");
		}
	}
}

```

output
```
 bazel build //:a.exe
INFO: Analyzed target //:a.exe (0 packages loaded, 0 targets configured).
INFO: Found 1 target...
ERROR: X:/work/github/rules_dotnet/docs/examples/mono/BUILD:3:11: Compiling net :a.exe failed (Exit 1)
a.cs(1,7): error CS0246: The type or namespace name 'System' could not be found (are you missing a using directive or an assembly reference?)
a.cs(6,18): error CS0518: Predefined type 'System.Object' is not defined or imported
a.cs(8,26): error CS0518: Predefined type 'System.String' is not defined or imported
a.cs(8,16): error CS0518: Predefined type 'System.Void' is not defined or imported
Target //:a.exe failed to build
Use --verbose_failures to see the command lines of failed build steps.
INFO: Elapsed time: 0.534s, Critical Path: 0.34s
INFO: 0 processes.
FAILED: Build did NOT complete successfully  
```

**Comment by lupin-de-mid** [comment]
Okey I found dependency :)

BUILD 
```
load("@io_bazel_rules_dotnet//dotnet:defs.bzl", "net_binary")

net_binary(
    name = "a.exe",
    srcs = [  "a.cs",   ],
    dotnet_context_data = "@io_bazel_rules_dotnet//:net_context_data_net46",
    native_deps = "@net_sdk_net46//:native_deps",
    target_framework = "net462",
    deps = [
        "@io_bazel_rules_dotnet//dotnet/stdlib.net/net462:system.dll",
    ],
 )
```

WORKSPACE
```
load("@bazel_tools//tools/build_defs/repo:git.bzl", "git_repository")
git_repository(
     name = "io_bazel_rules_dotnet",
     remote = "https://github.com/bazelbuild/rules_dotnet",
     branch = "master",
)
load("@io_bazel_rules_dotnet//dotnet:deps.bzl", "dotnet_repositories")
dotnet_repositories()
load("@io_bazel_rules_dotnet//dotnet:defs.bzl", "net_register_sdk",  "dotnet_register_toolchains")
dotnet_register_toolchains()
net_register_sdk("net46", name = "net_sdk_net46", tools_version = "net462")
```
Output

```
bazel build //:a.exe
ERROR: C:/users/user/_bazel_user/wwnhhnsh/external/io_bazel_rules_dotnet/dotnet/stdlib.net/net462/BUILD.bazel:7:14: no such package '@Microsoft.NETFramework.ReferenceAssemblies.net462.1.0.0//': The repository '@Microsoft.NETFramework.ReferenceAssemblies.net462.1.0.0' could not be resolved and referenced by '@io_bazel_rules_dotnet//dotnet/stdlib.net/net462:system.dll'
ERROR: C:/users/user/_bazel_user/wwnhhnsh/external/io_bazel_rules_dotnet/dotnet/stdlib.net/net462/BUILD.bazel:7:14: no such package '@Microsoft.NETFramework.ReferenceAssemblies.net462.1.0.0//': The repository '@Microsoft.NETFramework.ReferenceAssemblies.net462.1.0.0' could not be resolved and referenced by '@io_bazel_rules_dotnet//dotnet/stdlib.net/net462:system.dll'
ERROR: Analysis of target '//:a.exe' failed; build aborted: Analysis failed
INFO: Elapsed time: 0.130s
INFO: 0 processes.
FAILED: Build did NOT complete successfully (1 packages loaded, 1 target configured)

```

**Comment by lupin-de-mid** [comment]
Okey I found dependency :)

BUILD 
```
load("@io_bazel_rules_dotnet//dotnet:defs.bzl", "net_binary")

net_binary(
    name = "a.exe",
    srcs = [  "a.cs",   ],
    dotnet_context_data = "@io_bazel_rules_dotnet//:net_context_data_net46",
    native_deps = "@net_sdk_net46//:native_deps",
    target_framework = "net462",
    deps = [
        "@io_bazel_rules_dotnet//dotnet/stdlib.net/net462:system.dll",
    ],
 )
```

WORKSPACE
```
load("@bazel_tools//tools/build_defs/repo:git.bzl", "git_repository")
git_repository(
     name = "io_bazel_rules_dotnet",
     remote = "https://github.com/bazelbuild/rules_dotnet",
     branch = "master",
)
load("@io_bazel_rules_dotnet//dotnet:deps.bzl", "dotnet_repositories")
dotnet_repositories()
load("@io_bazel_rules_dotnet//dotnet:defs.bzl", "net_register_sdk",  "dotnet_register_toolchains")
dotnet_register_toolchains()
net_register_sdk("net46", name = "net_sdk_net46", tools_version = "net462")
```
Output

```
bazel build //:a.exe
ERROR: C:/users/user/_bazel_user/wwnhhnsh/external/io_bazel_rules_dotnet/dotnet/stdlib.net/net462/BUILD.bazel:7:14: no such package '@Microsoft.NETFramework.ReferenceAssemblies.net462.1.0.0//': The repository '@Microsoft.NETFramework.ReferenceAssemblies.net462.1.0.0' could not be resolved and referenced by '@io_bazel_rules_dotnet//dotnet/stdlib.net/net462:system.dll'
ERROR: C:/users/user/_bazel_user/wwnhhnsh/external/io_bazel_rules_dotnet/dotnet/stdlib.net/net462/BUILD.bazel:7:14: no such package '@Microsoft.NETFramework.ReferenceAssemblies.net462.1.0.0//': The repository '@Microsoft.NETFramework.ReferenceAssemblies.net462.1.0.0' could not be resolved and referenced by '@io_bazel_rules_dotnet//dotnet/stdlib.net/net462:system.dll'
ERROR: Analysis of target '//:a.exe' failed; build aborted: Analysis failed
INFO: Elapsed time: 0.130s
INFO: 0 processes.
FAILED: Build did NOT complete successfully (1 packages loaded, 1 target configured)

```

**Comment by tomaszstrejczek** [comment]
You need to call dotnet_repositories_nugets() after dotnet_register_toolchains() (from defs.bzl)
