### ISSUE TITLE
Fix version parsing to allow  "-preview" versions that contain  5 numeric parts

### ISSUE THREAD

**Issue by jwnewman12** [bazelbuild/rules_dotnet#202]
Unfortunately Microsoft has decided that "4.7.0-preview1.19504.10" is "official release" and that version comes up a lot when trying to pull many of the .netcore nuget packages. The rules reject it as an invalid version, as it contains 5 numeric parts, and it doesn't know what to do with the extra ".10".

You can reproduce this by using the nuget2bazel tool to add "Microsoft.AspNetCore.Server.Kestrel 2.2.0" and building. (We also cannot pull the bigger Microsoft.AspNetCore.App due to the unzip 0x80 bug https://github.com/bazelbuild/bazel/issues/9236)

```
ERROR: /home/john/.cache/bazel/_bazel_john/ac299c29b114bd436006869d5e507730/external/system.security.cryptography.cng/BUILD:63:20: in core_import_library rule @system.security.cryptography.cng//:netcoreapp3.1_core: 
Traceback (most recent call last):
    File "/home/john/.cache/bazel/_bazel_john/ac299c29b114bd436006869d5e507730/external/system.security.cryptography.cng/BUILD", line 63
        core_import_library(name = 'netcoreapp3.1_core')
    File "/home/john/.cache/bazel/_bazel_john/ac299c29b114bd436006869d5e507730/external/io_bazel_rules_dotnet/dotnet/private/rules/import.bzl", line 36, in _import_library_impl
        new_library(dotnet = ctx, <7 more arguments>)
    File "/home/john/.cache/bazel/_bazel_john/ac299c29b114bd436006869d5e507730/external/io_bazel_rules_dotnet/dotnet/private/rules/import.bzl", line 43, in new_library
        parse_version(ctx.attr.version)
    File "/home/john/.cache/bazel/_bazel_john/ac299c29b114bd436006869d5e507730/external/io_bazel_rules_dotnet/dotnet/private/rules/versions.bzl", line 15, in parse_version
        fail("Invalid version:", <1 more arguments>)
attribute 4.7.0-preview1.19504.10: Invalid version:
```

/external/system.security.cryptography.cng/BUILD contains:

```
core_import_library(
    name = "netcoreapp3.1_core",
    src = "lib/netcoreapp3.0/System.Security.Cryptography.Cng.dll",
    ref = "ref/netcoreapp3.0/System.Security.Cryptography.Cng.dll",
    deps = [
        
    ],
    data = [
            "lib/netcoreapp3.0/System.Security.Cryptography.Cng.dll",
    "lib/netcoreapp3.0/System.Security.Cryptography.Cng.xml",

    ],
    version = "4.7.0-preview1.19504.10",
)
```

Which if I search for that version, I find some pages from MS saying "ship with this version".

I've easily patched over it for now just by changing "4" -> "5" and ignoring the ".10". If for some reason we are worried about a preview ".11" appearing and breaking the build, to correctly support that would involve changing everything to 5 parts (no), or perhaps mathematically combining 19504 and 10 with a hashcode recipe.

**Comment by jwnewman12** [comment]
This can be closed, it's really only an issue if you're using the older nuget packages, Kestrel 2.2.0 was pulling -preview in. Instead, we should have been using the asp stdlib the entire time.

If anyone runs into this it's easy to patch.
