### ISSUE TITLE
Cannot test or run code that depends on nuget packages that include native binaries

### ISSUE THREAD

**Issue by jagobagascon** [bazelbuild/rules_dotnet#205]
I'm trying to test a Grpc interceptor implementation using `NUnit` and the `core_nunit3_test` rule. This test depends on `Grpc.Core` nuget package and `bazel` is giving me the following error when trying to run it:

```log
Unhandled exception. System.DllNotFoundException: Unable to load shared library 'grpc_csharp_ext.x64' or one of its dependencies. In order to help diagnose loading problems, consider setting the LD_DEBUG environment variable: libgrpc_csharp_ext.x64: cannot open shared object file: No such file or directory
   at Grpc.Core.Internal.NativeMethods.DllImportsFromSharedLib_x64.grpcsharp_redirect_log(GprLogDelegate callback)
   at Grpc.Core.Internal.NativeLogRedirector.Redirect(NativeMethods native) in /var/local/git/grpc/src/csharp/Grpc.Core/Internal/NativeLogRedirector.cs:line 49
   at Grpc.Core.Internal.NativeExtension..ctor() in /var/local/git/grpc/src/csharp/Grpc.Core/Internal/NativeExtension.cs:line 47
   at Grpc.Core.Internal.NativeExtension.Get() in /var/local/git/grpc/src/csharp/Grpc.Core/Internal/NativeExtension.cs:line 65
...
```

This is happening whenever I try to run or test code that depends on the `Grpc.Core` nuget package. `Grpc.Core` includes some native libraries that are required at runtime and for some reason `bazel` is not capable of finding them.

Is there any limitation to use nuget packages that include binaries? I'm using the `nuget_package` rule generated by  `nuget2bazel` to import the `Grpc.Core` dependency. Maybe I have to add the binaries in the generated `nuget_package` rule manually?

```bazel
core_binary(
    name = 'test.exe',
    srcs = [
        'Program.cs',
    ],
    deps = [
        "@grpc.core//:core",
        "@io_bazel_rules_dotnet//dotnet/stdlib.core:netstandard.dll",
    ]
)

core_nunit3_test(
    name = 'interceptor_test.dll',
    srcs = [ 'InterceptorTest.cs',],
    deps = [
        ':My.Library.dll',

        "@grpc.core//:core",
        "@nunit//:core",
    ],
)
```

**Comment by jagobagascon** [comment]
I just found a workaround for this. If I modify the `nuget_package` rule generated by `nuget2bazel` and add a reference to the binary files then the test works like a charm.
```bazel
nuget_package(
    name = "grpc.core",
    ...,
    core_files = {
        "netcoreapp2.0": [
            ...,
            "runtimes/linux-x64/native/libgrpc_csharp_ext.x64.so",
        ],
        "netcoreapp2.1": [
            ...,
            "runtimes/linux-x64/native/libgrpc_csharp_ext.x64.so",
        ],
        "netcoreapp3.0": [
            ...,
            "runtimes/linux-x64/native/libgrpc_csharp_ext.x64.so",
        ],
        "netcoreapp3.1": [
            ...,
            "runtimes/linux-x64/native/libgrpc_csharp_ext.x64.so",
        ],
)
```

So maybe this is a problem with `nuget2bazel`? It should detect and include these files in the generated rules.

**Comment by jagobagascon** [comment]
I added a PR that I believe fixes the issue.
