### ISSUE TITLE
Bazel CI: rules_dotnet failing in downstream pipeline with Bazel@HEAD

### ISSUE THREAD

**Issue by meteorcloudy** [bazelbuild/rules_dotnet#268]
https://buildkite.com/bazel/bazel-at-head-plus-downstream/builds/2273#a0af9fb0-30ce-4c1a-a8d2-998152915082
```
(02:11:36) ERROR: Traceback (most recent call last):
	File "/var/lib/buildkite-agent/.cache/bazel/_bazel_buildkite-agent/6b103ad44d5d96e1cc362a60a7eaee24/external/build_bazel_rules_apple/apple/internal/testing/ios_rules.bzl", line 62, column 61, in <toplevel>
		ios_ui_test_bundle = rule_factory.create_apple_bundling_rule(
	File "/var/lib/buildkite-agent/.cache/bazel/_bazel_buildkite-agent/6b103ad44d5d96e1cc362a60a7eaee24/external/build_bazel_rules_apple/apple/internal/rule_factory.bzl", line 904, column 55, in _create_apple_bundling_rule
		rule_attrs.append(_common_binary_linking_attrs(rule_descriptor))
	File "/var/lib/buildkite-agent/.cache/bazel/_bazel_buildkite-agent/6b103ad44d5d96e1cc362a60a7eaee24/external/build_bazel_rules_apple/apple/internal/rule_factory.bzl", line 218, column 21, in _common_binary_linking_attrs
		apple_common.objc_proto_aspect,
Error: 'apple_common' value has no field or method 'objc_proto_aspect'
```

Related Bazel issue: https://github.com/bazelbuild/bazel/issues/13811

**Comment by meteorcloudy** [comment]
rules_dotnet will be disabled in Bazel downstream until this is fixed, which means it won't get test coverage with Bazel@HEAD.

**Comment by purkhusid** [comment]
@meteorcloudy I'll take a look at this, I think it's only a matter of updating our https://github.com/rules-proto-grpc/rules_proto_grpc dependency

**Comment by purkhusid** [comment]
@meteorcloudy This should be fixed now

**Comment by meteorcloudy** [comment]
OK, rerunning with Bazel@HEAD https://buildkite.com/bazel/bazel-at-head-plus-disabled/builds/1137

**Comment by meteorcloudy** [comment]
Thanks, rules_dotnet is green with Bazel@HEAD, I'll re-enable it in the actual downstream pipeline.
