### ISSUE TITLE
nuget2bazel usage

### ISSUE THREAD

**Issue by err0r500** [bazelbuild/rules_dotnet#269]
Hello,
I try to use `nuget2bazel` in a test project. (dotnet core `v5.0.206` on the Fedora 35 & `v5.0.201` configured in the `.bazelrc`)

Here's a working `dotnet` command from the solution's root (where the `WORKSPACE` file lives) : 
```
dotnet add ./Lib/UseCase package Microsoft.Extensions.Logging --version 5.0.0
```

if I run 
```
bazel run @io_bazel_rules_dotnet//tools/nuget2bazel:nuget2bazel.exe -- add -p $PWD Microsoft.Extensions.Logging 5.0.0
```
or 
```
bazel run @io_bazel_rules_dotnet//tools/nuget2bazel:nuget2bazel.exe -- add -p $PWD/Lib/UseCase Microsoft.Extensions.Logging 5.0.0
```

I get a few packages installed in the `./packages` folder but it always ends up with
```
NU3028: Package 'System.Numerics.Vectors 4.5.0' from source 'https://api.nuget.org/v3/index.json': The author primary signature's timestamp found a chain building issue: UntrustedRoot: self signed certificate in certificate chain
NU3037: Package 'System.Numerics.Vectors 4.5.0' from source 'https://api.nuget.org/v3/index.json': The author primary signature validity period has expired.
NU3028: Package 'System.Numerics.Vectors 4.5.0' from source 'https://api.nuget.org/v3/index.json': The repository countersignature's timestamp found a chain building issue: UntrustedRoot: self signed certificate in certificate chain
NU3037: Package 'System.Numerics.Vectors 4.5.0' from source 'https://api.nuget.org/v3/index.json': The repository countersignature validity period has expired.
   at NuGet.PackageManagement.NuGetPackageManager.ExecuteNuGetProjectActionsAsync(NuGetProject nuGetProject, IEnumerable`1 nuGetProjectActions, INuGetProjectContext nuGetProjectContext, PackageDownloadContext downloadContext, CancellationToken token)
   at NuGet.PackageManagement.NuGetPackageManager.InstallPackageAsync(NuGetProject nuGetProject, PackageIdentity packageIdentity, ResolutionContext resolutionContext, INuGetProjectContext nuGetProjectContext, PackageDownloadContext downloadContext, IEnumerable`1 primarySources, IEnumerable`1 secondarySources, CancellationToken token)
   at nuget2bazel.AddCommand.DoWithProject(String nugetSource, String package, String version, ProjectBazelManipulator project, Boolean lowest)
   at nuget2bazel.Program.<>c.<<Main>b__0_0>d.MoveNext()
--- End of stack trace from previous location ---
   at nuget2bazel.Program.Main(String[] args)
   at nuget2bazel.Program.<Main>(String[] args)
```

Same thing happens with other packages (like `RabbitMQ.Client`). 
I guess I'm missing something obvious but I can't figure out what I'm doing wrong...

**Comment by purkhusid** [comment]
I've had some issues with using nuget2bazel as well so I don't personally use it but wrote a wrapper around https://fsprojects.github.io/Paket/ instead and it has been working great for me.

The plan is to replace nuget2bazel in the near future with a light wrapper around NuGet and this feature: https://github.com/NuGet/Home/wiki/Enable-repeatable-package-restore-using-lock-file

**Comment by purkhusid** [comment]
Going to close this since we are not going to be improving `nuget2bazel` and the `next` branch includes a more robust successor
