### ISSUE TITLE
nuget2bazel cannot sync Amazon.Lambda.TestUtilities Nuget package

### ISSUE THREAD

**Issue by njlr** [bazelbuild/rules_dotnet#278]
`nuget2config.json`

```json
{
  "externals": {},
  "dependencies": {
    "FSharp.Core": "6.0.3",
    "Expecto": "9.0.4",
    "Amazon.Lambda.RuntimeSupport": "1.7.0",
    "Amazon.Lambda.TestUtilities": "2.0.0"
  }
}
```

```bash
bazel run @io_bazel_rules_dotnet//tools/nuget2bazel:nuget2bazel.exe -- sync -p $PWD
```

```
Exception on adding Amazon.Lambda.TestUtilities:2.0.0
nuget2bazel.WorkspaceParser+UnexpectedToken: Exception of type 'nuget2bazel.WorkspaceParser+UnexpectedToken' was thrown.
   at nuget2bazel.WorkspaceParser.GetToken()
   at nuget2bazel.WorkspaceParser.GetArrayValue()
   at nuget2bazel.WorkspaceParser.RequireDictionaryList(TokenCode required)
   at nuget2bazel.WorkspaceParser.ParseEntry()
   at nuget2bazel.WorkspaceParser.ParseEntries()
   at nuget2bazel.WorkspaceWriter.AddEntry(String currentWorkspace, WorkspaceEntry toadd, Boolean indent)
   at nuget2bazel.ProjectBazelManipulator.AddEntry(WorkspaceEntry entry)
   at nuget2bazel.ProjectBazelManipulator.InstallPackageAsync(PackageIdentity packageIdentity, DownloadResourceResult downloadResourceResult, INuGetProjectContext nuGetProjectContext, CancellationToken token)
   at NuGet.PackageManagement.NuGetPackageManager.ExecuteInstallAsync(NuGetProject nuGetProject, PackageIdentity packageIdentity, DownloadResourceResult resourceResult, HashSet`1 packageWithDirectoriesToBeDeleted, INuGetProjectContext nuGetProjectContext, CancellationToken token)
   at NuGet.PackageManagement.NuGetPackageManager.ExecuteNuGetProjectActionsAsync(NuGetProject nuGetProject, IEnumerable`1 nuGetProjectActions, INuGetProjectContext nuGetProjectContext, PackageDownloadContext downloadContext, CancellationToken token)
   at NuGet.PackageManagement.NuGetPackageManager.ExecuteNuGetProjectActionsAsync(NuGetProject nuGetProject, IEnumerable`1 nuGetProjectActions, INuGetProjectContext nuGetProjectContext, PackageDownloadContext downloadContext, CancellationToken token)
   at NuGet.PackageManagement.NuGetPackageManager.ExecuteNuGetProjectActionsAsync(NuGetProject nuGetProject, IEnumerable`1 nuGetProjectActions, INuGetProjectContext nuGetProjectContext, PackageDownloadContext downloadContext, CancellationToken token)
   at NuGet.PackageManagement.NuGetPackageManager.InstallPackageAsync(NuGetProject nuGetProject, PackageIdentity packageIdentity, ResolutionContext resolutionContext, INuGetProjectContext nuGetProjectContext, PackageDownloadContext downloadContext, IEnumerable`1 primarySources, IEnumerable`1 secondarySources, CancellationToken token)
   at nuget2bazel.AddCommand.DoWithProject(String nugetSource, String package, String version, ProjectBazelManipulator project, Boolean lowest)
   at nuget2bazel.SyncCommand.Add(ILogger logger, String package, String version, ProjectBazelConfig prjConfig)
```

--------------------

```python
git_repository(
  name = "io_bazel_rules_dotnet",
  remote = "https://github.com/bazelbuild/rules_dotnet",
  commit = "66a708c64da9126c640b7ca62f03357740d06ea4",
  shallow_since = "1646997251 +0000",
)
```

**Comment by njlr** [comment]
Ah, turns out it doesn't like when you have commented lines in the `WORKSPACE` block that it generates. 

It should probably skip those lines or give a clearer error?

**Comment by njlr** [comment]
Note comments added due to this issue: https://github.com/bazelbuild/rules_dotnet/issues/279

**Comment by purkhusid** [comment]
I'm hoping that the improved NuGet support on the `next` branch will handle all these issues.

**Comment by purkhusid** [comment]
Going to close this since `nuget2bazel` will be deprecated when the `next` branch is merged.
