### ISSUE TITLE
examples build issues

### ISSUE THREAD

**Issue by doomtr666** [bazelbuild/rules_dotnet#354]
Hi,

I've a build issue with some of the examples:

```
PS I:\Dev\rules_dotnet\examples> bazel run //paket:paket_example.exe      
INFO: Analyzed target //paket:paket_example.exe (0 packages loaded, 0 targets configured).
ERROR: I:/dev/rules_dotnet/examples/paket/BUILD.bazel:3:14: Compiling paket_example.exe failed: (Exit -532462766): compiler_wrapper.bat failed: error executing command (from target //paket:paket_example.exe) external\rules_dotnet\dotnet\private\compiler_wrapper.bat external/dotnet_x86_64-pc-windows-msvc/dotnet.exe external/dotnet_x86_64-pc-windows-msvc/sdk/7.0.101/FSharp/fsc.dll ... (remaining 1 argument skipped)
Unhandled exception. System.Globalization.CultureNotFoundException: Only the invariant culture is supported in globalization-invariant mode. See https://aka.ms/GlobalizationInvariantMode for more information. (Parameter 'name')
en-US is an invalid culture identifier.
   at System.Globalization.CultureInfo..ctor(String name, Boolean useUserOverride)
   at FSharp.Compiler.Driver.main1(CompilationThreadToken ctok, String[] argv, LegacyReferenceResolver legacyReferenceResolver, Boolean bannerAlreadyPrinted, ReduceMemoryFlag reduceMemoryUsage, CopyFSharpCoreFlag defaultCopyFSharpCore, Exiter exiter, IDiagnosticsLoggerProvider diagnosticsLoggerProvider, DisposablesTracker disposables) in D:\a\_work\1\s\src\Compiler\Driver\fsc.fs:line 490
   at FSharp.Compiler.Driver.CompileFromCommandLineArguments(CompilationThreadToken ctok, String[] argv, LegacyReferenceResolver legacyReferenceResolver, Boolean bannerAlreadyPrinted, ReduceMemoryFlag reduceMemoryUsage, CopyFSharpCoreFlag defaultCopyFSharpCore, Exiter exiter, IDiagnosticsLoggerProvider 
loggerProvider, FSharpOption`1 tcImportsCapture, FSharpOption`1 dynamicAssemblyCreator) in D:\a\_work\1\s\src\Compiler\Driver\fsc.fs:line 1189
   at FSharp.Compiler.CommandLineMain.main(String[] argv) in D:\a\_work\1\s\src\fsc\fscmain.fs:line 84
   at FSharp.Compiler.DiagnosticsLogger.DiagnosticsLoggerExtensions.ReraiseIfWatsonable(Exception exn) in D:\a\_work\1\s\src\Compiler\Facilities\DiagnosticsLogger.fs:line 419
   at FSharp.Compiler.DiagnosticsLogger.DiagnosticsLoggerExtensions.DiagnosticsLogger.ErrorRecovery(DiagnosticsLogger x, Exception exn, Range m) in D:\a\_work\1\s\src\Compiler\Facilities\DiagnosticsLogger.fs:line 470
   at FSharp.Compiler.DiagnosticsLogger.errorRecovery(Exception exn, Range m) in D:\a\_work\1\s\src\Compiler\Facilities\DiagnosticsLogger.fs:line 571
   at FSharp.Compiler.CommandLineMain.main(String[] argv) in D:\a\_work\1\s\src\fsc\fscmain.fs:line 101
Target //paket:paket_example.exe failed to build
Use --verbose_failures to see the command lines of failed build steps.
INFO: Elapsed time: 14.881s, Critical Path: 14.63s
INFO: 2 processes: 2 internal.
FAILED: Build did NOT complete successfully
ERROR: Build failed. Not running target
```

**Comment by doomtr666** [comment]
If I change "DOTNET_SYSTEM_GLOBALIZATION_INVARIANT": "0" in both dotnet\private\rules\csharp\actions\csharp_assembly.bzl and dotnet\private\rules\fsharp\actions\fsharp_assembly.bzl, all examples work fine, but certainly causes regression on other platforms.  
I've the same issue when running paket2bazel.

**Comment by purkhusid** [comment]
I think what might be happening is that you don't have `--incompatible_strict_action_env` enabled and the ENV on your system is polluting the actions. Could you try running with this flag and see if you get the same errors?

**Comment by doomtr666** [comment]
Windows 10 
bazel 6.2.0
no particular flags nor bazelrc

**Comment by doomtr666** [comment]
Same issue with  --incompatible_strict_action_env.

```
PS I:\Dev\rules_dotnet\examples> bazel clean --expunge; bazel test --incompatible_strict_action_env -s //...
INFO: Starting clean.
Starting local Bazel server and connecting to it...
INFO: Analyzed 25 targets (161 packages loaded, 6147 targets configured).
INFO: Found 19 targets and 6 test targets...
WARNING: cleared convenience symlink(s) bazel-bin, bazel-testlogs because their destinations would be ambiguous
SUBCOMMAND: # //diamond:Bottom [action 'Compiling Bottom', configuration: 4b57520e875603cc15d5d045c61613d3ed8700ce84b5cbf76754c212571bb5c3, execution platform: @local_config_platform//:host]
cd /d C:/users/chris/_bazel_chris/a4tcaekx/execroot/examples
  SET DOTNET_CLI_HOME=external/dotnet_x86_64-pc-windows-msvc
    SET DOTNET_SYSTEM_GLOBALIZATION_INVARIANT=1
  external\rules_dotnet\dotnet\private\compiler_wrapper.bat external/dotnet_x86_64-pc-windows-msvc/dotnet.exe external/dotnet_x86_64-pc-windows-msvc/sdk/7.0.101/Roslyn/bincore/csc.dll @bazel-out/x64_windows-fastbuild-ST-83e840a93b96/bin/diamond/bazelout/netstandard1.4/Bottom.dll-0.params
# Configuration: 4b57520e875603cc15d5d045c61613d3ed8700ce84b5cbf76754c212571bb5c3
# Execution platform: @local_config_platform//:host
SUBCOMMAND: # //diamond:Bottom [action 'Compiling Bottom', configuration: 9417ec47d41e1c82c19017dc806b4fdbc10aaece45a68eb1c8bf0664f47b17f0, execution platform: @local_config_platform//:host]
cd /d C:/users/chris/_bazel_chris/a4tcaekx/execroot/examples
  SET DOTNET_CLI_HOME=external/dotnet_x86_64-pc-windows-msvc
    SET DOTNET_SYSTEM_GLOBALIZATION_INVARIANT=1
  external\rules_dotnet\dotnet\private\compiler_wrapper.bat external/dotnet_x86_64-pc-windows-msvc/dotnet.exe external/dotnet_x86_64-pc-windows-msvc/sdk/7.0.101/Roslyn/bincore/csc.dll @bazel-out/x64_windows-fastbuild-ST-60423d879a60/bin/diamond/bazelout/net40/Bottom.dll-0.params
# Configuration: 9417ec47d41e1c82c19017dc806b4fdbc10aaece45a68eb1c8bf0664f47b17f0
# Execution platform: @local_config_platform//:host
SUBCOMMAND: # //fsharp_type_provider/type_provider_lib:type_provider_lib [action 'Compiling type_provider_lib', configuration: dc8a53c148a1c57518c57c68acc8be6c09b6798f5a59d6a3025b341c0c963db1, execution platform: @local_config_platform//:host]
cd /d C:/users/chris/_bazel_chris/a4tcaekx/execroot/examples
  SET DOTNET_CLI_HOME=external/dotnet_x86_64-pc-windows-msvc
    SET DOTNET_SYSTEM_GLOBALIZATION_INVARIANT=1
  external\rules_dotnet\dotnet\private\compiler_wrapper.bat external/dotnet_x86_64-pc-windows-msvc/dotnet.exe external/dotnet_x86_64-pc-windows-msvc/sdk/7.0.101/FSharp/fsc.dll @bazel-out/x64_windows-fastbuild-ST-19c30ace4401/bin/fsharp_type_provider/type_provider_lib/bazelout/net6.0/type_provider_lib.dll-0.params
# Configuration: dc8a53c148a1c57518c57c68acc8be6c09b6798f5a59d6a3025b341c0c963db1
# Execution platform: @local_config_platform//:host
SUBCOMMAND: # //basic_fsharp:lib [action 'Compiling lib', configuration: dc8a53c148a1c57518c57c68acc8be6c09b6798f5a59d6a3025b341c0c963db1, execution platform: @local_config_platform//:host]
cd /d C:/users/chris/_bazel_chris/a4tcaekx/execroot/examples
  SET DOTNET_CLI_HOME=external/dotnet_x86_64-pc-windows-msvc
    SET DOTNET_SYSTEM_GLOBALIZATION_INVARIANT=1
  external\rules_dotnet\dotnet\private\compiler_wrapper.bat external/dotnet_x86_64-pc-windows-msvc/dotnet.exe external/dotnet_x86_64-pc-windows-msvc/sdk/7.0.101/FSharp/fsc.dll @bazel-out/x64_windows-fastbuild-ST-19c30ace4401/bin/basic_fsharp/bazelout/net6.0/lib.dll-0.params
# Configuration: dc8a53c148a1c57518c57c68acc8be6c09b6798f5a59d6a3025b341c0c963db1
# Execution platform: @local_config_platform//:host
SUBCOMMAND: # //diamond:Bottom [action 'Compiling Bottom', configuration: be4a043d1c9cccad0c46ca0e73b2a17eee6923d2618d33a9d8c39033c87aca8b, execution platform: @local_config_platform//:host]
cd /d C:/users/chris/_bazel_chris/a4tcaekx/execroot/examples
  SET DOTNET_CLI_HOME=external/dotnet_x86_64-pc-windows-msvc
    SET DOTNET_SYSTEM_GLOBALIZATION_INVARIANT=1
  external\rules_dotnet\dotnet\private\compiler_wrapper.bat external/dotnet_x86_64-pc-windows-msvc/dotnet.exe external/dotnet_x86_64-pc-windows-msvc/sdk/7.0.101/Roslyn/bincore/csc.dll @bazel-out/x64_windows-fastbuild-ST-2aeeb0c41b78/bin/diamond/bazelout/net48/Bottom.dll-0.params
# Configuration: be4a043d1c9cccad0c46ca0e73b2a17eee6923d2618d33a9d8c39033c87aca8b
# Execution platform: @local_config_platform//:host
SUBCOMMAND: # //basic_csharp:lib [action 'Compiling lib (internals ref-only dll)', configuration: 68b6b12fe166c84b9aee9070a5ec9d1c69e6bafd4eb1a3c854cf1d13257d226b, execution platform: @local_config_platform//:host]
cd /d C:/users/chris/_bazel_chris/a4tcaekx/execroot/examples
  SET DOTNET_CLI_HOME=external/dotnet_x86_64-pc-windows-msvc
    SET DOTNET_SYSTEM_GLOBALIZATION_INVARIANT=1
  external\rules_dotnet\dotnet\private\compiler_wrapper.bat external/dotnet_x86_64-pc-windows-msvc/dotnet.exe external/dotnet_x86_64-pc-windows-msvc/sdk/7.0.101/Roslyn/bincore/csc.dll @bazel-out/x64_windows-fastbuild-ST-bc69725b45eb/bin/basic_csharp/bazelout/net6.0/ref/lib.dll-0.params
# Configuration: 68b6b12fe166c84b9aee9070a5ec9d1c69e6bafd4eb1a3c854cf1d13257d226b
# Execution platform: @local_config_platform//:host
SUBCOMMAND: # //basic_csharp:lib [action 'Compiling lib', configuration: 68b6b12fe166c84b9aee9070a5ec9d1c69e6bafd4eb1a3c854cf1d13257d226b, execution platform: @local_config_platform//:host]
cd /d C:/users/chris/_bazel_chris/a4tcaekx/execroot/examples
  SET DOTNET_CLI_HOME=external/dotnet_x86_64-pc-windows-msvc
    SET DOTNET_SYSTEM_GLOBALIZATION_INVARIANT=1
  external\rules_dotnet\dotnet\private\compiler_wrapper.bat external/dotnet_x86_64-pc-windows-msvc/dotnet.exe external/dotnet_x86_64-pc-windows-msvc/sdk/7.0.101/Roslyn/bincore/csc.dll @bazel-out/x64_windows-fastbuild-ST-bc69725b45eb/bin/basic_csharp/bazelout/net6.0/lib.dll-0.params
# Configuration: 68b6b12fe166c84b9aee9070a5ec9d1c69e6bafd4eb1a3c854cf1d13257d226b
# Execution platform: @local_config_platform//:host
SUBCOMMAND: # //diamond:Bottom [action 'Compiling Bottom', configuration: 1dcb0fc0e93ee238043dd0beae534a156020860efada8f3c7f2edd338f1ad2b0, execution platform: @local_config_platform//:host]
cd /d C:/users/chris/_bazel_chris/a4tcaekx/execroot/examples
  SET DOTNET_CLI_HOME=external/dotnet_x86_64-pc-windows-msvc
    SET DOTNET_SYSTEM_GLOBALIZATION_INVARIANT=1
  external\rules_dotnet\dotnet\private\compiler_wrapper.bat external/dotnet_x86_64-pc-windows-msvc/dotnet.exe external/dotnet_x86_64-pc-windows-msvc/sdk/7.0.101/Roslyn/bincore/csc.dll @bazel-out/x64_windows-fastbuild-ST-1533a92d02db/bin/diamond/bazelout/net40/Bottom.dll-0.params
# Configuration: 1dcb0fc0e93ee238043dd0beae534a156020860efada8f3c7f2edd338f1ad2b0
# Execution platform: @local_config_platform//:host
SUBCOMMAND: # //diamond:Bottom [action 'Compiling Bottom', configuration: c1b2306891f627004b122dd0ff8dcd0649451dbf256f4741d53c15d45529dc71, execution platform: @local_config_platform//:host]
cd /d C:/users/chris/_bazel_chris/a4tcaekx/execroot/examples
  SET DOTNET_CLI_HOME=external/dotnet_x86_64-pc-windows-msvc
    SET DOTNET_SYSTEM_GLOBALIZATION_INVARIANT=1
  external\rules_dotnet\dotnet\private\compiler_wrapper.bat external/dotnet_x86_64-pc-windows-msvc/dotnet.exe external/dotnet_x86_64-pc-windows-msvc/sdk/7.0.101/Roslyn/bincore/csc.dll @bazel-out/x64_windows-fastbuild-ST-8af1ed98a55a/bin/diamond/bazelout/netstandard1.4/Bottom.dll-0.params
# Configuration: c1b2306891f627004b122dd0ff8dcd0649451dbf256f4741d53c15d45529dc71
# Execution platform: @local_config_platform//:host
SUBCOMMAND: # @rules_dotnet//dotnet/private/tools/apphost_shimmer:apphost_shimmer [action 'Compiling apphost_shimmer [for tool]', configuration: 7e019a8e5e9be64f0a22dfe94d8b74ca615e0528fdd782d4119ebec025cbcec3, execution platform: @local_config_platform//:host]
cd /d C:/users/chris/_bazel_chris/a4tcaekx/execroot/examples
  SET DOTNET_CLI_HOME=external/dotnet_x86_64-pc-windows-msvc
    SET DOTNET_SYSTEM_GLOBALIZATION_INVARIANT=1
  external\rules_dotnet\dotnet\private\compiler_wrapper.bat external/dotnet_x86_64-pc-windows-msvc/dotnet.exe external/dotnet_x86_64-pc-windows-msvc/sdk/7.0.101/Roslyn/bincore/csc.dll @bazel-out/x64_windows-opt-exec-2B5CBBC6-ST-19c30ace4401/bin/external/rules_dotnet/dotnet/private/tools/apphost_shimmer/bazelout/net6.0/apphost_shimmer.dll-0.params
# Configuration: 7e019a8e5e9be64f0a22dfe94d8b74ca615e0528fdd782d4119ebec025cbcec3
# Execution platform: @local_config_platform//:host
SUBCOMMAND: # //fsharp_type_provider/type_provider_lib:type_provider_lib [action 'Compiling type_provider_lib', configuration: 68b6b12fe166c84b9aee9070a5ec9d1c69e6bafd4eb1a3c854cf1d13257d226b, execution platform: @local_config_platform//:host]
cd /d C:/users/chris/_bazel_chris/a4tcaekx/execroot/examples
  SET DOTNET_CLI_HOME=external/dotnet_x86_64-pc-windows-msvc
    SET DOTNET_SYSTEM_GLOBALIZATION_INVARIANT=1
  external\rules_dotnet\dotnet\private\compiler_wrapper.bat external/dotnet_x86_64-pc-windows-msvc/dotnet.exe external/dotnet_x86_64-pc-windows-msvc/sdk/7.0.101/FSharp/fsc.dll @bazel-out/x64_windows-fastbuild-ST-bc69725b45eb/bin/fsharp_type_provider/type_provider_lib/bazelout/net6.0/type_provider_lib.dll-0.params
# Configuration: 68b6b12fe166c84b9aee9070a5ec9d1c69e6bafd4eb1a3c854cf1d13257d226b
# Execution platform: @local_config_platform//:host
INFO: From Compiling Bottom:
warning CS8021: No value for RuntimeMetadataVersion found. No assembly containing System.Object was found nor was a value for RuntimeMetadataVersion specified through options.
INFO: From Compiling Bottom:
warning CS8021: No value for RuntimeMetadataVersion found. No assembly containing System.Object was found nor was a value for RuntimeMetadataVersion specified through options.
INFO: From Compiling Bottom:
warning CS8021: No value for RuntimeMetadataVersion found. No assembly containing System.Object was found nor was a value for RuntimeMetadataVersion specified through options.
SUBCOMMAND: # //basic_fsharp:lib [action 'Compiling lib', configuration: 68b6b12fe166c84b9aee9070a5ec9d1c69e6bafd4eb1a3c854cf1d13257d226b, execution platform: @local_config_platform//:host]
cd /d C:/users/chris/_bazel_chris/a4tcaekx/execroot/examples
  SET DOTNET_CLI_HOME=external/dotnet_x86_64-pc-windows-msvc
    SET DOTNET_SYSTEM_GLOBALIZATION_INVARIANT=1
  external\rules_dotnet\dotnet\private\compiler_wrapper.bat external/dotnet_x86_64-pc-windows-msvc/dotnet.exe external/dotnet_x86_64-pc-windows-msvc/sdk/7.0.101/FSharp/fsc.dll @bazel-out/x64_windows-fastbuild-ST-bc69725b45eb/bin/basic_fsharp/bazelout/net6.0/lib.dll-0.params
# Configuration: 68b6b12fe166c84b9aee9070a5ec9d1c69e6bafd4eb1a3c854cf1d13257d226b
# Execution platform: @local_config_platform//:host
SUBCOMMAND: # //diamond:Right [action 'Compiling Right', configuration: 917a28db42086aa05647a79702eabe6a37639241bad84289641f12f7ae2c94f7, execution platform: @local_config_platform//:host]
cd /d C:/users/chris/_bazel_chris/a4tcaekx/execroot/examples
  SET DOTNET_CLI_HOME=external/dotnet_x86_64-pc-windows-msvc
    SET DOTNET_SYSTEM_GLOBALIZATION_INVARIANT=1
  external\rules_dotnet\dotnet\private\compiler_wrapper.bat external/dotnet_x86_64-pc-windows-msvc/dotnet.exe external/dotnet_x86_64-pc-windows-msvc/sdk/7.0.101/Roslyn/bincore/csc.dll @bazel-out/x64_windows-fastbuild-ST-016668b1a922/bin/diamond/bazelout/netstandard2.0/Right.dll-0.params
# Configuration: 917a28db42086aa05647a79702eabe6a37639241bad84289641f12f7ae2c94f7
# Execution platform: @local_config_platform//:host
SUBCOMMAND: # //diamond:Left [action 'Compiling Left', configuration: 964482be5d5bc26c7b42a9b7de8334f920b5aa496d68274ee49a002d1d6fd5d5, execution platform: @local_config_platform//:host]
cd /d C:/users/chris/_bazel_chris/a4tcaekx/execroot/examples
  SET DOTNET_CLI_HOME=external/dotnet_x86_64-pc-windows-msvc
    SET DOTNET_SYSTEM_GLOBALIZATION_INVARIANT=1
  external\rules_dotnet\dotnet\private\compiler_wrapper.bat external/dotnet_x86_64-pc-windows-msvc/dotnet.exe external/dotnet_x86_64-pc-windows-msvc/sdk/7.0.101/Roslyn/bincore/csc.dll @bazel-out/x64_windows-fastbuild-ST-64f722f12299/bin/diamond/bazelout/net45/Left.dll-0.params
# Configuration: 964482be5d5bc26c7b42a9b7de8334f920b5aa496d68274ee49a002d1d6fd5d5
# Execution platform: @local_config_platform//:host
SUBCOMMAND: # //expecto:expecto_example.dll [action 'Compiling expecto_example.dll', configuration: 20b1104e357c7f54c8007919fa6a0469d39c65d6a7c43e931076923b654f06d1, execution platform: @local_config_platform//:host]
cd /d C:/users/chris/_bazel_chris/a4tcaekx/execroot/examples
  SET DOTNET_CLI_HOME=external/dotnet_x86_64-pc-windows-msvc
    SET DOTNET_SYSTEM_GLOBALIZATION_INVARIANT=1
  external\rules_dotnet\dotnet\private\compiler_wrapper.bat external/dotnet_x86_64-pc-windows-msvc/dotnet.exe external/dotnet_x86_64-pc-windows-msvc/sdk/7.0.101/FSharp/fsc.dll @bazel-out/x64_windows-fastbuild-ST-19c30ace4401/bin/expecto/bazelout/net6.0/expecto_example.dll.dll-0.params
# Configuration: 20b1104e357c7f54c8007919fa6a0469d39c65d6a7c43e931076923b654f06d1
# Execution platform: @local_config_platform//:host
INFO: From Compiling Bottom:
warning CS8021: No value for RuntimeMetadataVersion found. No assembly containing System.Object was found nor was a value for RuntimeMetadataVersion specified through options.
INFO: From Compiling Bottom:
warning CS8021: No value for RuntimeMetadataVersion found. No assembly containing System.Object was found nor was a value for RuntimeMetadataVersion specified through options.
SUBCOMMAND: # //basic_csharp:lib [action 'Compiling lib', configuration: dc8a53c148a1c57518c57c68acc8be6c09b6798f5a59d6a3025b341c0c963db1, execution platform: @local_config_platform//:host]
cd /d C:/users/chris/_bazel_chris/a4tcaekx/execroot/examples
  SET DOTNET_CLI_HOME=external/dotnet_x86_64-pc-windows-msvc
    SET DOTNET_SYSTEM_GLOBALIZATION_INVARIANT=1
  external\rules_dotnet\dotnet\private\compiler_wrapper.bat external/dotnet_x86_64-pc-windows-msvc/dotnet.exe external/dotnet_x86_64-pc-windows-msvc/sdk/7.0.101/Roslyn/bincore/csc.dll @bazel-out/x64_windows-fastbuild-ST-19c30ace4401/bin/basic_csharp/bazelout/net6.0/lib.dll-0.params
# Configuration: dc8a53c148a1c57518c57c68acc8be6c09b6798f5a59d6a3025b341c0c963db1
# Execution platform: @local_config_platform//:host
SUBCOMMAND: # //diamond:Left [action 'Compiling Left', configuration: a18a694d1bc004dabe66a30dbeb5a07259643af8df656981d650ed05cb3ca49d, execution platform: @local_config_platform//:host]
cd /d C:/users/chris/_bazel_chris/a4tcaekx/execroot/examples
  SET DOTNET_CLI_HOME=external/dotnet_x86_64-pc-windows-msvc
    SET DOTNET_SYSTEM_GLOBALIZATION_INVARIANT=1
  external\rules_dotnet\dotnet\private\compiler_wrapper.bat external/dotnet_x86_64-pc-windows-msvc/dotnet.exe external/dotnet_x86_64-pc-windows-msvc/sdk/7.0.101/Roslyn/bincore/csc.dll @bazel-out/x64_windows-fastbuild-ST-aa04514520ef/bin/diamond/bazelout/net45/Left.dll-0.params
# Configuration: a18a694d1bc004dabe66a30dbeb5a07259643af8df656981d650ed05cb3ca49d
# Execution platform: @local_config_platform//:host
SUBCOMMAND: # //aspnetcore:aspnetcore [action 'Compiling aspnetcore', configuration: dc8a53c148a1c57518c57c68acc8be6c09b6798f5a59d6a3025b341c0c963db1, execution platform: @local_config_platform//:host]
cd /d C:/users/chris/_bazel_chris/a4tcaekx/execroot/examples
  SET DOTNET_CLI_HOME=external/dotnet_x86_64-pc-windows-msvc
    SET DOTNET_SYSTEM_GLOBALIZATION_INVARIANT=1
  external\rules_dotnet\dotnet\private\compiler_wrapper.bat external/dotnet_x86_64-pc-windows-msvc/dotnet.exe external/dotnet_x86_64-pc-windows-msvc/sdk/7.0.101/Roslyn/bincore/csc.dll @bazel-out/x64_windows-fastbuild-ST-19c30ace4401/bin/aspnetcore/bazelout/net6.0/aspnetcore.dll-0.params
# Configuration: dc8a53c148a1c57518c57c68acc8be6c09b6798f5a59d6a3025b341c0c963db1
# Execution platform: @local_config_platform//:host
SUBCOMMAND: # //diamond:Right [action 'Compiling Right', configuration: dcc9c9b9d50d80bb8a6bf3ce77bf296330ada5c69d2fcf869a838a1e38f4de68, execution platform: @local_config_platform//:host]
cd /d C:/users/chris/_bazel_chris/a4tcaekx/execroot/examples
  SET DOTNET_CLI_HOME=external/dotnet_x86_64-pc-windows-msvc
    SET DOTNET_SYSTEM_GLOBALIZATION_INVARIANT=1
  external\rules_dotnet\dotnet\private\compiler_wrapper.bat external/dotnet_x86_64-pc-windows-msvc/dotnet.exe external/dotnet_x86_64-pc-windows-msvc/sdk/7.0.101/Roslyn/bincore/csc.dll @bazel-out/x64_windows-fastbuild-ST-856abcf65127/bin/diamond/bazelout/netstandard2.0/Right.dll-0.params
# Configuration: dcc9c9b9d50d80bb8a6bf3ce77bf296330ada5c69d2fcf869a838a1e38f4de68
# Execution platform: @local_config_platform//:host
SUBCOMMAND: # @rules_dotnet//dotnet/private/tools/apphost_shimmer:apphost_shimmer [action 'Compiling apphost_shimmer [for tool]', configuration: fd83100a36aa995b5858696b0d04158585547ecd006dc961d610b57b2a59c8cb, execution platform: @local_config_platform//:host]
cd /d C:/users/chris/_bazel_chris/a4tcaekx/execroot/examples
  SET DOTNET_CLI_HOME=external/dotnet_x86_64-pc-windows-msvc
    SET DOTNET_SYSTEM_GLOBALIZATION_INVARIANT=1
  external\rules_dotnet\dotnet\private\compiler_wrapper.bat external/dotnet_x86_64-pc-windows-msvc/dotnet.exe external/dotnet_x86_64-pc-windows-msvc/sdk/7.0.101/Roslyn/bincore/csc.dll @bazel-out/x64_windows-opt-exec-2B5CBBC6-ST-bc69725b45eb/bin/external/rules_dotnet/dotnet/private/tools/apphost_shimmer/bazelout/net6.0/apphost_shimmer.dll-0.params
# Configuration: fd83100a36aa995b5858696b0d04158585547ecd006dc961d610b57b2a59c8cb
# Execution platform: @local_config_platform//:host
ERROR: I:/dev/rules_dotnet/examples/expecto/BUILD.bazel:6:12: Compiling expecto_example.dll failed: (Exit -532462766): compiler_wrapper.bat failed: error executing command (from target //expecto:expecto_example.dll) external\rules_dotnet\dotnet\private\compiler_wrapper.bat external/dotnet_x86_64-pc-windows-msvc/dotnet.exe external/dotnet_x86_64-pc-windows-msvc/sdk/7.0.101/FSharp/fsc.dll ... (remaining 1 argument skipped)
Unhandled exception. System.Globalization.CultureNotFoundException: Only the invariant culture is supported in globalization-invariant mode. See https://aka.ms/GlobalizationInvariantMode for more information. (Parameter 'name')
en-US is an invalid culture identifier.
   at System.Globalization.CultureInfo..ctor(String name, Boolean useUserOverride)
   at FSharp.Compiler.Driver.main1(CompilationThreadToken ctok, String[] argv, LegacyReferenceResolver legacyReferenceResolver, Boolean bannerAlreadyPrinted, ReduceMemoryFlag reduceMemoryUsage, CopyFSharpCoreFlag defaultCopyFSharpCore, Exiter exiter, IDiagnosticsLoggerProvider diagnosticsLoggerProvider, DisposablesTracker disposables) in D:\a\_work\1\s\src\Compiler\Driver\fsc.fs:line 490
   at FSharp.Compiler.Driver.CompileFromCommandLineArguments(CompilationThreadToken ctok, String[] argv, LegacyReferenceResolver legacyReferenceResolver, Boolean bannerAlreadyPrinted, ReduceMemoryFlag reduceMemoryUsage, CopyFSharpCoreFlag defaultCopyFSharpCore, Exiter exiter, IDiagnosticsLoggerProvider 
loggerProvider, FSharpOption`1 tcImportsCapture, FSharpOption`1 dynamicAssemblyCreator) in D:\a\_work\1\s\src\Compiler\Driver\fsc.fs:line 1189
   at FSharp.Compiler.CommandLineMain.main(String[] argv) in D:\a\_work\1\s\src\fsc\fscmain.fs:line 84
   at FSharp.Compiler.DiagnosticsLogger.DiagnosticsLoggerExtensions.ReraiseIfWatsonable(Exception exn) in D:\a\_work\1\s\src\Compiler\Facilities\DiagnosticsLogger.fs:line 419
   at FSharp.Compiler.DiagnosticsLogger.DiagnosticsLoggerExtensions.DiagnosticsLogger.ErrorRecovery(DiagnosticsLogger x, Exception exn, Range m) in D:\a\_work\1\s\src\Compiler\Facilities\DiagnosticsLogger.fs:line 470
   at FSharp.Compiler.DiagnosticsLogger.errorRecovery(Exception exn, Range m) in D:\a\_work\1\s\src\Compiler\Facilities\DiagnosticsLogger.fs:line 571
   at FSharp.Compiler.CommandLineMain.main(String[] argv) in D:\a\_work\1\s\src\fsc\fscmain.fs:line 101
INFO: Elapsed time: 20.808s, Critical Path: 1.46s
INFO: 66 processes: 61 internal, 5 local.
FAILED: Build did NOT complete successfully
//basic_csharp:lib_test                                               NO STATUS
//basic_fsharp:lib_test                                               NO STATUS
//fsharp_type_provider:fsharp_type_provider                           NO STATUS
//runfiles_csharp:runfiles_test                                       NO STATUS
//runfiles_fsharp:runfiles_test                                       NO STATUS
//expecto:expecto_example.dll                                   FAILED TO BUILD

Executed 0 out of 6 tests: 1 fails to build and 5 were skipped.
```

**Comment by purkhusid** [comment]
Sorry about the delayed answers, been busy recently. I think I might remove these envs from the compiliation actions since I'm not so sure that they are wanted in general. The reason for them is that without setting the invariant culture the build fails on the remote workers because they don't have libicu installed. I'll just add a note to the readme about this instead.

I'll try to get this fixed today or tomorrow.

**Comment by purkhusid** [comment]
This should not be fixed on master. Let me know if you still encounter any issues.

**Comment by doomtr666** [comment]
Fixed for me. Thank you !
