### ISSUE TITLE
Error Specified license file doesn't exist with Bazel@HEAD

### ISSUE THREAD

**Issue by sgowroji** [bazelbuild/rules_dotnet#363]
https://buildkite.com/bazel/bazel-at-head-plus-downstream/builds/3212#0189beb8-6f47-4d7b-a775-b8c7cb7ad9ca

Platform : Windows

Logs:
```
 ERROR: Traceback (most recent call last):
	File "C:/b/mnqfk7or/external/platforms/BUILD", line 8, column 8, in <toplevel>
		license(
	File "C:/b/mnqfk7or/external/rules_license/rules/license.bzl", line 110, column 13, in license
		fail("Specified license file doesn't exist: %s" % license_text)
Error in fail: Specified license file doesn't exist: LICENSE
(04:05:55) ERROR: C:/b/mnqfk7or/external/platforms/BUILD: no such target '@platforms//:incompatible': target 'incompatible' not declared in package '' defined by C:/b/mnqfk7or/external/platforms/BUILD (Tip: use `query "@platforms//:*"` to see all the targets in that package)
(04:05:55) ERROR: Analysis of target '//docs:csharp_library' failed; build aborted: no such target '@platforms//:incompatible': target 'incompatible' not declared in package '' defined by C:/b/mnqfk7or/external/platforms/BUILD (Tip: use `query "@platforms//:*"` to see all the targets in that package)

```

Steps : 
```
git clone https://github.com/bazelbuild/rules_dotnet.git
git reset fa1e285adf34fbf4fc59bbfc65b6d33795b4cc67 --hard
export USE_BAZEL_VERSION=896b358cdeb386411eb65088c1d0f5b4a4819fd2
bazel build //...
```
Assuming this commit might have caused the breakage https://github.com/bazelbuild/bazel/commit/7ed631eaf2636254c12501e4c27840aa0ce430bf

CC Greenteam @meteorcloudy

**Comment by sgowroji** [comment]
CC @fedemartinezdev

**Comment by meteorcloudy** [comment]
@aiuto Have you seen similar error before?

**Comment by aiuto** [comment]
Updating to license 0.0.7 doesn't seem to be the cause.
The BCR points to https://github.com/bazelbuild/platforms/releases/download/0.0.7/platforms-0.0.7.tar.gz,
and if you inspect that, the file LICENSE is there.

I tried with bazel 6.3.1, and  ISTM that rules_dotnet is picking up a very old platforms.  Looking at bazel-rules_dotnet/external/platforms/cpu/BUILD, it seems to be from a version a little after platforms 0.0.4.

With last_green, I get the newer version of @platforms, but it seems oddly corrupted.

```
$ more bazel-rules_dotnet/external/platforms/BUILD
load("@rules_license//rules:license.bzl", "license")

package(
    default_applicable_licenses = [":license"],
    default_visibility = ["//visibility:public"],
)

license(
    name = "license",
    license_kinds = [
        "@rules_license//licenses/spdx:Apache-2.0",
    ],
    license_text = "LICENSE",
)

$ ls ls bazel-rules_dotnet/external/platforms
BUILD  WORKSPACE  cpu  os
```
Huh???? Where is the LICENSE file.  bazel's distdir_deps.bzl points to https://mirror.bazel.build/github.com/bazelbuild/platforms/releases/download/0.0.7/platforms-0.0.7.tar.gz, but the file there also has LICENSE.

Can this be a cache problem?

**Comment by sgowroji** [comment]
Hi Team, Gentle ping for the update on this issue.

**Comment by purkhusid** [comment]
Do you think the issue is on rules_dotnet side or on the Bazel side?

**Comment by meteorcloudy** [comment]
This is probably a breaking change on Bazel's side which needs some fixes from rules_dotnet.

**Comment by sgowroji** [comment]
Hi @purkhusid Can you please have a look on the above failures. Thanks!

**Comment by purkhusid** [comment]
This has been fixed on master
