### ISSUE TITLE
Errors encountered while applying Starlark transition with Bazel@HEAD

### ISSUE THREAD

**Issue by sgowroji** [bazelbuild/rules_dotnet#364]
https://buildkite.com/bazel/bazel-at-head-plus-downstream/builds/3252#018a15dd-efdf-4443-95b8-a35992d212c5

Platform :  Ubuntu, Windows, MacOS

Logs : 
```
ERROR: Traceback (most recent call last):
	File "/private/var/tmp/_bazel_buildkite/e1ff1b15b991f24287f9bf0490c303ec/external/rules_dotnet/dotnet/private/transitions/tfm_transition.bzl", line 33, column 233, in _impl
		return dicts.add({"@rules_dotnet//dotnet:target_framework": transitioned_tfm}, {"@rules_dotnet//dotnet:rid": runtime_identifier}, FRAMEWORK_COMPATABILITY_TRANSITION_OUTPUTS[transitioned_tfm], RID_COMPATABILITY_TRANSITION_OUTPUTS[runtime_identifier])
Error: key select({Label("@rules_dotnet//dotnet/private:linux-x64"): "linux-x64", Label("@rules_dotnet//dotnet/private:linux-arm64"): "linux-arm64", Label("@rules_dotnet//dotnet/private:macos-x64"): "osx-x64", Label("@rules_dotnet//dotnet/private:macos-arm64"): "osx-arm64", Label("@rules_dotnet//dotnet/private:windows-x64"): "win-x64", Label("@rules_dotnet//dotnet/private:windows-arm64"): "win-arm64"}) not found in dictionary
(04:17:49) ERROR: /Users/buildkite/builds/bk-imacpro-2/bazel-downstream-projects/rules_dotnet/examples/fsharp_type_provider/BUILD.bazel:6:18: Errors encountered while applying Starlark transition
(04:17:49) ERROR: Analysis of target '//fsharp_type_provider:fsharp_type_provider' failed; build aborted
```

Steps:
```
git clone https://github.com/bazelbuild/rules_dotnet.git && cd rules_dotnet/examples
git reset 1912a7aa017f7d43139b8d3b41584b96aa1ff3dc --hard
export USE_BAZEL_VERSION=ceddfb1ece1f8ed7ff81558fa1751e6526df031b
bazel build //...
```
CC Greenteam @SalmaSamy

**Comment by sgowroji** [comment]
Hi @purkhusid/ @tomaszstrejczek Can you have al ook at the above failures with Bazel@HEAD. Thanks!

**Comment by purkhusid** [comment]
I'll take a look ASAP

**Comment by purkhusid** [comment]
@sgowroji I'm not sure if this is a bug with rules_dotnet or Bazel. For some reason I can't use `select` without an default condition and it's failing with:
```
FATAL: bazel crashed due to an internal error. Printing stack trace:
java.lang.RuntimeException: Unrecoverable error while evaluating node 'ConfiguredTargetKey{label=//dotnet/private/tests/dependency_resolution/diamond_dependencies/d:d, config=BuildConfigurationKey[7b6b170266f99fa31b40616d26c2a2f781cbbd21b93561dc9de07920befe38ff]}' (requested by nodes )
        at com.google.devtools.build.skyframe.AbstractParallelEvaluator$Evaluate.run(AbstractParallelEvaluator.java:550)
        at com.google.devtools.build.lib.concurrent.AbstractQueueVisitor$WrappedRunnable.run(AbstractQueueVisitor.java:414)
        at java.base/java.util.concurrent.ForkJoinTask$RunnableExecuteAction.exec(Unknown Source)
        at java.base/java.util.concurrent.ForkJoinTask.doExec(Unknown Source)
        at java.base/java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(Unknown Source)
        at java.base/java.util.concurrent.ForkJoinPool.scan(Unknown Source)
        at java.base/java.util.concurrent.ForkJoinPool.runWorker(Unknown Source)
        at java.base/java.util.concurrent.ForkJoinWorkerThread.run(Unknown Source)
Caused by: java.lang.IllegalStateException: lookup failed on attribute private_deps: configurable attribute "private_deps" in //dotnet/private/tests/dependency_resolution/diamond_dependencies/d:d doesn't match this configuration. Would a default condition help?
```

Note that the rule in question has an incoming rule transition and an outgoing transition on the field mentioned in the error. But the transitions should be transitioning to a value that is in the `select`.

**Comment by sgowroji** [comment]
@gregestren Can you guide on the  above [comment](https://github.com/bazelbuild/rules_dotnet/issues/364#issuecomment-1708449099). Thanks!

**Comment by gregestren** [comment]
This might be related to @aranguyen 's refactoring of the incoming rule transition logic (to make it more permissive). 

See https://github.com/bazelbuild/bazel/commit/ceddfb1ece1f8ed7ff81558fa1751e6526df031b but @aranguyen can provide more context. I know there were a few followup tweaks to handle some corner cases.

**Comment by aranguyen** [comment]
@purkhusid Does your select() statement without default condition relies on applying rule transition for it to be resolved properly? If so, the change https://github.com/bazelbuild/bazel/commit/ceddfb1ece1f8ed7ff81558fa1751e6526df031b is responsible for the crash. And I'm working on a fix for this so please stay tuned.

**Comment by purkhusid** [comment]
@aranguyen Yes, the select statement relies on the rule transition to be applied. Do you have an issue I could subscribe to for updates?

**Comment by aranguyen** [comment]
@purkhusid This is fixed in https://github.com/bazelbuild/bazel/commit/a0e0dc5326ba2d77d36034b2916b25617d1a565c
