### ISSUE TITLE
paket2bazel raises null path error

### ISSUE THREAD

**Issue by donoewan** [bazelbuild/rules_dotnet#418]
On running:

` ~/rules_dotnet/examples$ bazel run @rules_dotnet//tools/paket2bazel:paket2bazel.exe -- --dependencies-file $(pwd)/paket.dependencies  --output-folder $(pwd)/deps`

The following output is generated:

```
INFO: Analyzed target @@rules_dotnet~override//tools/paket2bazel:paket2bazel.exe (301 packages loaded, 1718 targets configured).
INFO: Found 1 target...
Target @@rules_dotnet~override//tools/paket2bazel:paket2bazel.exe up-to-date (nothing to build)
INFO: Elapsed time: 6.276s, Critical Path: 1.76s
INFO: 9 processes: 7 internal, 2 linux-sandbox.
INFO: Build completed successfully, 9 total actions
INFO: Running command line: bazel-bin/external/rules_dotnet~override/tools/paket2bazel/paket2bazel.exe/net6.0/paket2bazel.exe.dll.sh --dependencies-file /home/paul/rules_dotnet/examples/paket.dependencies --output-folder /home/paul/rules_dotnet/examples/deps
Unhandled exception. System.TypeInitializationException: The type initializer for 'Paket.Constants' threw an exception.
 ---> System.TypeInitializationException: The type initializer for '<StartupCode$Paket-Core>.$Paket.Constants' threw an exception.
 ---> System.ArgumentNullException: Value cannot be null. (Parameter 'path1')
   at System.ArgumentNullException.Throw(String paramName)
   at System.IO.Path.Combine(String path1, String path2)
   at Paket.Constants.Environment.GetFolderPath(SpecialFolder sf) in C:\code\Paket\src\Paket.Core\Common\Constants.fs:line 73
   at Paket.Constants.getEnvDir(SpecialFolder specialPath) in C:\code\Paket\src\Paket.Core\Common\Constants.fs:line 83
   at <StartupCode$Paket-Core>.$Paket.Constants..cctor() in C:\code\Paket\src\Paket.Core\Common\Constants.fs:line 87
   --- End of inner exception stack trace ---
   at Paket.Constants..cctor()
   --- End of inner exception stack trace ---
   at Paket.Constants.get_PaketRestoreHashFilePath()
   at Paket.RestoreProcess.readRestoreCache(FileInfo lockFileName) in C:\code\Paket\src\Paket.Core\Installation\RestoreProcess.fs:line 666
   at Paket.RestoreProcess.readCache@721(RestoreProjectOptions projectFile, FileInfo lockFileName, Boolean canCacheRestore, Unit unitVar0) in C:\code\Paket\src\Paket.Core\Installation\RestoreProcess.fs:line 725
   at Paket.RestoreProcess.Restore(String dependenciesFileName, RestoreProjectOptions projectFile, Boolean force, FSharpOption`1 group, Boolean ignoreChecks, Boolean failOnChecks, FSharpOption`1 targetFrameworks, FSharpOption`1 outputPath, Boolean skipRestoreTargetsExtraction) in C:\code\Paket\src\Paket.Core\Installation\RestoreProcess.fs:line 734
   at Paket.Dependencies.SimplePackagesRestore() in C:\code\Paket\src\Paket.Core\PublicAPI.fs:line 389
   at Paket2Bazel.Paket.getDependencies(String dependenciesFile, Dictionary`2 cache) in ./external/rules_dotnet~override/tools/paket2bazel/Paket.fs:line 161
   at Paket2Bazel.Main.main(String[] argv) in ./external/rules_dotnet~override/tools/paket2bazel/Main.fs:line 44
/home/paul/.cache/bazel/_bazel_paul/c5019ec22e2fd31dc8a1ff55fc0400fe/execroot/_main/bazel-out/k8-fastbuild-ST-218d85e2318e/bin/external/rules_dotnet~override/tools/paket2bazel/paket2bazel.exe/net6.0/paket2bazel.exe.dll.sh: line 35: 10549 Aborted                 (core dumped) $(rlocation rules_dotnet~override~dotnet~dotnet_x86_64-unknown-linux-gnu/dotnet) exec $(rlocation rules_dotnet~override/tools/paket2bazel/paket2bazel.exe/net6.0/paket2bazel.exe.dll) "$@"
```

I tried this with my own project but the error is also raised on running it in the examples folder of the rules_dotnet repository.

**OS**: Ubuntu 20.04.6 LTS 5.15.0-97-generic
**Bazel**: 7.0.2
**rules_dotnet**: master, v0.14.0, v0.13.0, v0.12.0

**Comment by purkhusid** [comment]
This should be fixed on master. Reopen if you still encounter this error after upgrading.

**Comment by donoewan** [comment]
I still can reproduce this after upgrading (master 626e28effb14f87de8375186ebb59911a16b71fb).
