### ISSUE TITLE
[Bazel CI] ERROR: An error occurred during the fetch of repository rules_dotnet_dev_nuget_packages_extension with Bazel@HEAD


### ISSUE THREAD

**Issue by sgowroji** [bazelbuild/rules_dotnet#421]
CI: https://buildkite.com/bazel/bazel-at-head-plus-downstream/builds/3716#018e3609-27ef-44b6-a03c-5aba25e8d3f2

 Platform: Windows

 Logs: 
```
ERROR: [0mAn error occurred during the fetch of repository '_main~rules_dotnet_dev_nuget_packages_extension~nuget.microsoft.netcore.app.runtime.win-x64.v6.0.8':
Exception: C:/b/cache/repos/v1/content_addressable/sha256/38f308a5ea5a54387770ab1efcadfed3ec556fe22d9dd3d9d1d14c0171810837/file (Permission denied)
ERROR: [0m<builtin>: fetching nuget_archive rule //:_main~rules_dotnet_dev_nuget_packages_extension~nuget.microsoft.netcore.app.runtime.win-x64.v6.0.8: Traceback (most recent call last):
Exception: C:/b/cache/repos/v1/content_addressable/sha256/38f308a5ea5a54387770ab1efcadfed3ec556fe22d9dd3d9d1d14c0171810837/file (Permission denied)
ERROR: [0mno such package '@@_main~rules_dotnet_dev_nuget_packages_extension~nuget.microsoft.netcore.app.runtime.win-x64.v6.0.8//': java.io.IOException: C:/b/cache/repos/v1/content_addressable/sha256/38f308a5ea5a54387770ab1efcadfed3ec556fe22d9dd3d9d1d14c0171810837/file (Permission denied)
ERROR: [0mC:/b/qxmqlmv5/external/_main~rules_dotnet_dev_nuget_packages_extension~paket.rules_dotnet_dev_nuget_packages/microsoft.netcore.app.runtime.win-x64/6.0.8/BUILD.bazel:5:15: @@_main~rules_dotnet_dev_nuget_packages_extension~paket.rules_dotnet_dev_nuget_packages//microsoft.netcore.app.runtime.win-x64/6.0.8:6.0.8 depends on @@_main~rules_dotnet_dev_nuget_packages_extension~nuget.microsoft.netcore.app.runtime.win-x64.v6.0.8//:microsoft.netcore.app.runtime.win-x64.6.0.8.nupkg in repository @@_main~rules_dotnet_dev_nuget_packages_extension~nuget.microsoft.netcore.app.runtime.win-x64.v6.0.8 which failed to fetch. no such package '@@_main~rules_dotnet_dev_nuget_packages_extension~nuget.microsoft.netcore.app.runtime.win-x64.v6.0.8//': java.io.IOException: C:/b/cache/repos/v1/content_addressable/sha256/38f308a5ea5a54387770ab1efcadfed3ec556fe22d9dd3d9d1d14c0171810837/file (Permission denied)
ERROR: [0mAnalysis of target '//dotnet/private/tests/use_as_tool/fsharp:run_self_contained' failed; build aborted: Analysis failed
ERROR: [0mBuild did NOT complete successfully
FAILED:[0m 
FAILED:[0m 
Error: The command exited with status 1[0m
error: exit status 1
``` 
 Culprit: https://github.com/bazelbuild/bazel/commit/af6e090583e9d88a5af9f39e702bb3fhttps://github.com/bazelbuild/bazel/commit/8eade046a85670a940f7cf1a4f06f13https://github.com/bazelbuild/bazel/commit/63be83f833020210c5daf6c3fa6667e9ff637140

 Steps:
  ``` 
 git clone https://github.com/bazelbuild/rules_dotnet
git reset 2af3c4d68510d9631d71e61caea919c28636b218  --hard
export USE_BAZEL_VERSION=98f29db0ac47b4b3c75bccdcfda20ffd50521597
bazel build //... 
 ``` 
 CC Greenteam @wyverald

**Comment by sgowroji** [comment]
Rules\_dotnet is also failing on windows at 

1.  [https://buildkite.com/bazel/bazel-at-head-plus-downstream/builds/3730#018e54e2-d206-4abd-a9ff-187f6fd63416](https://buildkite.com/bazel/bazel-at-head-plus-downstream/builds/3730#018e54e2-d206-4abd-a9ff-187f6fd63416)

   2.  [https://buildkite.com/bazel/bazel-at-head-plus-downstream/builds/3730#018e54e2-d24c-400e-b5a4-96d38ae2422b](https://buildkite.com/bazel/bazel-at-head-plus-downstream/builds/3730#018e54e2-d24c-400e-b5a4-96d38ae2422b)

Logs:

```
ERROR: An error occurred during the fetch of repository 'rules_dotnet~~rules_dotnet_nuget_packages_extension~nuget.nunitlite.v3.12.0':
   Traceback (most recent call last):
	File "C:/b/yda6y4t5/external/rules_dotnet~/dotnet/private/rules/nuget/nuget_archive.bzl", line 320, column 29, in _nuget_archive_impl
		urls = _get_package_urls(ctx, ctx.attr.sources, auth, ctx.attr.id, ctx.attr.version)
	File "C:/b/yda6y4t5/external/rules_dotnet~/dotnet/private/rules/nuget/nuget_archive.bzl", line 277, column 26, in _get_package_urls
		rctx.download(source, auth = auth, output = "index.json")
Error in download: java.io.IOException: C:/b/cache/repos/v1/content_addressable/sha256/38f308a5ea5a54387770ab1efcadfed3ec556fe22d9dd3d9d1d14c0171810837/file (Permission denied)
(04:13:29) ERROR: <builtin>: fetching nuget_archive rule //:rules_dotnet~~rules_dotnet_nuget_packages_extension~nuget.nunitlite.v3.12.0: Traceback (most recent call last):
	File "C:/b/yda6y4t5/external/rules_dotnet~/dotnet/private/rules/nuget/nuget_archive.bzl", line 320, column 29, in _nuget_archive_impl
		urls = _get_package_urls(ctx, ctx.attr.sources, auth, ctx.attr.id, ctx.attr.version)
	File "C:/b/yda6y4t5/external/rules_dotnet~/dotnet/private/rules/nuget/nuget_archive.bzl", line 277, column 26, in _get_package_urls
		rctx.download(source, auth = auth, output = "index.json")
Error in download: java.io.IOException: C:/b/cache/repos/v1/content_addressable/sha256/38f308a5ea5a54387770ab1efcadfed3ec556fe22d9dd3d9d1d14c0171810837/file (Permission denied)
(04:13:29) ERROR: no such package '@@rules_dotnet~~rules_dotnet_nuget_packages_extension~nuget.nunitlite.v3.12.0//': java.io.IOException: C:/b/cache/repos/v1/content_addressable/sha256/38f308a5ea5a54387770ab1efcadfed3ec556fe22d9dd3d9d1d14c0171810837/file (Permission denied)
(04:13:29) ERROR: C:/b/yda6y4t5/external/rules_dotnet~~rules_dotnet_nuget_packages_extension~paket.rules_dotnet_nuget_packages/nunitlite/3.12.0/BUILD.bazel:5:15: @@rules_dotnet~~rules_dotnet_nuget_packages_extension~paket.rules_dotnet_nuget_packages//nunitlite/3.12.0:3.12.0 depends on @@rules_dotnet~~rules_dotnet_nuget_packages_extension~nuget.nunitlite.v3.12.0//:libs in repository @@rules_dotnet~~rules_dotnet_nuget_packages_extension~nuget.nunitlite.v3.12.0 which failed to fetch. no such package '@@rules_dotnet~~rules_dotnet_nuget_packages_extension~nuget.nunitlite.v3.12.0//': java.io.IOException: C:/b/cache/repos/v1/content_addressable/sha256/38f308a5ea5a54387770ab1efcadfed3ec556fe22d9dd3d9d1d14c0171810837/file (Permission denied)
(04:13:29) ERROR: Analysis of target '//basic_fsharp:lib_test' failed; build aborted: Analysis failed
```

**Comment by Wyverald** [comment]
hmm, cc @fmeum -- could the failure be actually related to https://github.com/bazelbuild/bazel/commit/8eade04?

**Comment by fmeum** [comment]
It's very likely that the commit causes the failure we see. However, this doesn't mean that the problematic behavior didn't exist before, just that we can now encounter it even within a single Bazel server.

Since we now do seem to have a way of producing these failures in CI, should we try to fix it forward? I looked into the `FileSystemUtils` implementations and it looks like `touchFile` isn't really implemented in an atomic fashion (in particular not a way that is safe to run concurrently with other file accesses). I could try to fix that and see whether that resolves the issue.

**Comment by fmeum** [comment]
I can reproduce this in an integration test: https://github.com/bazelbuild/bazel/pull/21779

I modified Bazel to print stack traces and it looks like `FileSystemUtils#moveFile` uses the non-atomic copy path for some reason. I will investigate this further.

**Comment by fmeum** [comment]
My observations so far:
* `renameTo` on Windows isn't atomic since it separately deletes and moves the file. I think that we could just use `Files.move(..., ATOMIC_MOVE, REPLACE_EXISTING)` to implement it, but I may be missing some particular behavior in which this differs. It may end up fixing other concurrency issues.
* For the particular use case in `RepositoryCache`, this is still not good enough: The file to be replaced with the move may be subject to concurrent read access, which results in `AccessDeniedException` on Windows. Unfortunately, `Files.move` is [hardcoded to use `REPLACE_EXISTING`](https://github.com/openjdk/jdk/blob/af15c68f3ccb72537b0a60d942f12d600f13ebb6/src/java.base/windows/classes/sun/nio/fs/WindowsFileCopy.java#L324) on Windows. Otherwise we could potentially detect this case via a `FileAlreadyExistsException`. Instead, I will try to ignore the `AccessDeniedException` when the file exists after the attempted move.

@meteorcloudy I would be very interested in your thoughts on this.

**Comment by Wyverald** [comment]
nice debugging!
